wpengine/faustjs

examples/next/getting-started/src/components/Pagination.tsx, examples/next/getting-started/src/components/Posts.tsx
=> doc: (#287) using core types for pagination and posts

package-lock.json
This PR resolves #290 and fixes the `trim-newlines` dependabot issue.
=> fix: (#290) trim-newlines dependabot alert

packages/next/src/client.ts
=> feat: (#326) adding wrappers for gqless queries

package-lock.json, packages/core/package.json, packages/next/package.json, packages/react/package.json
=> make: (#336) move to 0.7.1

examples/next/getting-started/package.json, examples/next/getting-started/src/pages/404.tsx, examples/next/getting-started/src/pages/[...pageUri].tsx, examples/next/getting-started/src/pages/category/[categorySlug]/index.tsx, examples/next/getting-started/src/pages/custom-page.tsx, examples/next/getting-started/src/pages/index.tsx, examples/next/getting-started/src/pages/posts/[postSlug]/index.tsx, examples/next/getting-started/src/pages/posts/index.tsx, package-lock.json
=> fix: (#338) replaced `useGeneralSettings` with `useQuery`

packages/core/package-lock.json, packages/core/package.json, packages/core/src/utils/convert.ts, packages/core/test/utils/convert.test.ts
cleanup unused code and dependencies to fix missing dep in vite/sveltekit
=> Fix: remove old code to fix missing deps

packages/next/package.json, packages/react/package.json, scripts/version.js
This will make sure to update package versions and keep them in sync whenever you run the `minor` or `patch` scripts from root.
=> chore: adding version sync script

internal/website/docs/tutorial/dev-env-setup.mdx
=> docs: (#311) Create development environment setup docs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> make: (#363) Issue templates

plugins/wpe-headless/readme.txt
Tagged 0.5.6 to kick off CircleCI deployment processes
=> make: Release 0.5.6 wpe-headless plugin

plugins/wpe-headless/includes/settings/views/headless-settings.php, plugins/wpe-headless/readme.txt, plugins/wpe-headless/wpe-headless.php
=> make: (#375) release wpe-headless plugin 0.5.7

plugins/wpe-headless/includes/auth/functions.php, plugins/wpe-headless/includes/graphql/callbacks.php
=> feat: (#383) mutation for generating authorization codes

.gitignore, CONTRIBUTING.md, DEVELOPMENT.md, README.md, examples/next/getting-started/README.md, examples/next/getting-started/src/components/Header.tsx, examples/next/getting-started/src/pages/index.tsx, examples/react/getting-started/README.md, examples/react/getting-started/src/components/Header.tsx, examples/react/getting-started/src/pages/home.tsx, package-lock.json, packages/core/README.md, packages/core/package.json, packages/core/tsconfig.json, packages/headless/README.md, packages/next/README.md, packages/next/package.json, packages/next/tsconfig.json, packages/react/README.md, packages/react/package.json, packages/react/tsconfig.json, plugins/wpe-headless/includes/settings/callbacks.php, plugins/wpe-headless/includes/settings/views/headless-settings.php
=> chore: headless-framework -> faustjs

plugins/wpe-headless/includes/deny-public-access/callbacks.php
Use [`add_query_arg()`](https://developer.wordpress.org/reference/functions/add_query_arg/) to include query params in the request uri when redirecting to the frontend url.
Resolves #170
=> fix: (#170) Redirect public URLs to the frontend with query params

internal/website/src/components/Features/HomepageFeatures.js
Fix docs homepage features icon
=> fix: docs features icon

packages/core/.npmignore, packages/core/LICENSE, packages/next/.npmignore, packages/next/LICENSE, packages/react/.npmignore, packages/react/LICENSE
=> Only include necessary files in npm packages

docs/release-notes.mdx, internal/website/docusaurus.config.js, internal/website/sidebars.js
=> Create a docs page for release notes

plugins/wpe-headless/composer.json, plugins/wpe-headless/composer.lock
=> Fix `phpass` composer dependency issue

DEVELOPMENT.md
Add our git workflows to the development guide.
=> add git workflow docs

internal/website/blog/2021-12-03-upgrading-to-faustwp.md, internal/website/docusaurus.config.js
https://hcixzyt38dn5ak04xxcqc36lf.js.wpenginepowered.com
=> Add blog entry for FaustWP upgrade guide

examples/next/getting-started/src/pages/index.tsx, examples/next/getting-started/src/scss/pages/home.module.scss, package-lock.json
Added SSG/ISR info under features list to help users better understand how the example project handles caching.
Added some new features under the features section of the example project detailing SSG/ISR/Atlas.
=> 🔨 refactor(examples): Add caching info to example

.changeset/gorgeous-elephants-bathe.md
Changeset follow up for https://github.com/wpengine/faustjs/pull/738
=> Include changeset for latest FaustWP work

plugins/faustwp/readme.txt
Bumping our tested up to version as no issues were found.
=> Bump WP tested version

.github/workflows/lint-plugin.yml, plugins/faustwp/composer.json, plugins/faustwp/includes/deny-public-access/functions.php, plugins/faustwp/includes/replacement/graphql-callbacks.php, plugins/faustwp/includes/settings/callbacks.php
Squashing minor linter warnings/errors for what is currently in canary.
=> Linting fixes

plugins/faustwp/readme.txt
Adding myself as a new contributor to the FaustWP plugin 😄
=> Add new contributor

.changeset/gorgeous-elephants-bathe.md, .github/workflows/lint-plugin.yml, examples/next/getting-started/package.json, internal/website/docusaurus.config.js, internal/website/src/pages/index.js, plugins/faustwp/CHANGELOG.md, plugins/faustwp/composer.json, plugins/faustwp/faustwp.php, plugins/faustwp/includes/deny-public-access/callbacks.php, plugins/faustwp/includes/deny-public-access/functions.php, plugins/faustwp/includes/replacement/graphql-callbacks.php, plugins/faustwp/includes/settings/callbacks.php, plugins/faustwp/package.json, plugins/faustwp/readme.txt
* Enforce node engine
* faustwp@0.7.3
* Add Algolia search
=> `canary` -> `main`

README.md
Add readme image.
None
None
None
None
None
=> Add readme image

internal/website/docs/going-to-production/deployment.mdx, internal/website/docs/going-to-production/optimizations.mdx, internal/website/sidebars.js
Documentation for deploy your Faust.js app and some optimizations you can make when going to production.
1. Added a "Going to Production" sidebar column
2. Added a "Deploy Your Faust.js App" page to the "Going to Production" section
3. Added a "Production Optimizations" page to the "Going to Production" section
Staging URL:
https://hcixzyt38dn5ak04xxcqc36lf.js.wpenginepowered.com/
=> 📝 docs(deployments): Prod Faust.js docs

internal/website/package-lock.json
Just an `npm update` without changing any of our semver constraints.
Running the docs site locally everything appears to be working the same as before.
=> Update docs dependencies

README.md
Adds a notice on pull requests to the repo's readme.
=> Add pull request notice to repo readme

internal/website/docs/next/guides/testing-with-jest.mdx, internal/website/sidebars.js
Include a guide with contents/examples on how to test Faust.js apps with Jest.
=> Create a guide for testing Faust.js apps with Jest

.github/workflows/lint-plugin.yml, plugins/faustwp/.gitignore, plugins/faustwp/composer.json, plugins/faustwp/composer.lock, plugins/faustwp/phpunit-multisite.xml.dist, plugins/faustwp/phpunit.xml.dist, plugins/faustwp/tests/integration/admin-menus/test-callbacks.php, plugins/faustwp/tests/integration/detect-conflicts/test-callbacks.php, plugins/faustwp/tests/integration/detect-conflicts/test-functions.php, plugins/faustwp/tests/integration/replacement/test-graphql-callbacks.php, plugins/faustwp/tests/integration/replacement/test-replacement-callbacks.php, plugins/faustwp/tests/integration/replacement/test-replacement-functions.php, plugins/faustwp/tests/integration/settings/test-callbacks.php
This change updates PHPUnit to it's latest version.
=> [MERL-316] Upgrade PHPUnit

package-lock.json
Ran `npm install --package-lock-only` on the monorepo root `package-lock.json` to reflect recent changes.
=> Update monorepo `package-lock.json`

package-lock.json
Related ticket: https://wpengine.atlassian.net/browse/MERL-333
=> [MERL-333] build(security): Bump undici to 5.5.1

internal/website/package-lock.json, internal/website/package.json
A quick update to the latest Docusaurus Beta (2.0-18 - 2.0-21)
N/A
Visual testing only
N/A
N/A
N/A
=> Update docusaurus to latest beta

internal/website/blog/2022-08-03-sprint-15-update.md
=> Add Sprint-15 Blog Post

.eslintrc.js, examples/next/faust-nx/package.json, package-lock.json
=> Fix React 18 types causing FaustNX build failures

.eslintrc.js, packages/core/src/utils/assert.ts, packages/faust-nx/src/auth/client/accessToken.ts, packages/faust-nx/src/client.ts, packages/faust-nx/src/components/FaustNXProvider.tsx, packages/faust-nx/src/components/WordPressTemplate.tsx, packages/faust-nx/src/getTemplate.ts, packages/faust-nx/src/getWordPressProps.tsx, packages/faust-nx/src/index.ts, packages/faust-nx/src/lib/getWpUrl.ts, packages/faust-nx/src/server/auth/cookie.ts, packages/faust-nx/src/server/auth/token.ts, packages/faust-nx/src/server/router/index.ts, packages/faust-nx/src/utils/assert.ts, packages/faust-nx/src/utils/convert.ts
This PR resolves the outstanding FaustNX linting issues.
=> Resolve FaustNX linting issues

examples/next/faust-nx/faustnx.config.js, examples/next/faust-nx/package.json, examples/next/faust-nx/pages/_app.tsx, examples/next/getting-started/package.json, package-lock.json, packages/faust-nx/package.json, packages/faust-nx/src/config/index.ts, packages/faust-nx/src/hooks/index.ts
This PR introduces the plugin system using [@wordpress/hooks](https://www.npmjs.com/package/@wordpress/hooks) behind an `experimental` flag.
1. Checkout the PR
2. Run `npm run build -w faust-nx`
3. Replace the `examples/next/faust-nx/faustnx.config.js` file contents with:
```js
import { setConfig } from 'faust-nx';
import templates from './wp-templates';
class HelloWorld {
apply(hooks) {
console.log(hooks);
}
}
/**
* @type {import('faust-nx').FaustNXConfig}
**/
export default setConfig({
templates,
experimentalPlugins: [new HelloWorld()],
});
```
4. Run `npm run dev -w faust-nx-getting-started`
5. Notice the plugin's `apply()` method gets called and the `hooks` argument gets consoled.
=> Implement experimental plugin system

examples/next/faust-nx/pages/sample-page.tsx, package-lock.json, packages/faust-nx/src/getProps.ts
Remove the `client` property from the Next.js file based pages type interface.
=> Fix Next.js file based pages

.github/workflows/e2e-next-example.yml, .github/workflows/e2e-test-plugin.yml, .github/workflows/lint-packages.yml, .github/workflows/test-packages.yml, packages/next/src/server/getProps.tsx
Removes the step in our GitHub actions that remove the `package-lock.json` file that was causing discrepencies between our local build and CI/CD builds.
=> Remove package-lock.json steps and fix broken tests

internal/website/blog/2022-09-14-sprint-18-update.md
=> Add Sprint 18 blog post

.changeset/config.json
Removes references to faust-nx from changeset
=> build(changeset): Fix unused faust-nx references

DEVELOPMENT.md
=> Remove obsolete reference in dev documentation

.changeset/config.json
https://github.com/wpengine/faustjs/pull/1034
=> Fix failing build

DEVELOPMENT.md, packages/core/package.json
=> Trigger Build (#1036)

internal/website/blog/2022-09-30-sprint-19-update.md
=> Sprint 19 blog post

.github/workflows/e2e-next-example.yml, .github/workflows/e2e-test-plugin.yml, .github/workflows/lint-packages.yml, .github/workflows/release-packages.yml, .github/workflows/test-packages.yml, DEVELOPMENT.md, internal/website/blog/2022-09-30-sprint-19-update.md, packages/core/package.json, packages/next/package.json, packages/react/package.json
=> Blog post deployment for 30 Sep, 2022

internal/legacy.faustjs.org/docusaurus.config.js
1. Run the old docs using the `npm run docs-legacy` command
2. Observe the banner message on the top
=> MERL-547: Add Deprecation Banner on legacy.faustjs.org

internal/faustjs.org/package-lock.json, internal/faustjs.org/package.json, internal/legacy.faustjs.org/package-lock.json, internal/legacy.faustjs.org/package.json
Update GOT version for dependabot via docusaurus upgrade.
=> MERL-346: update to latest version for docusaurus for got issue

examples/next/getting-started/gqty.config.js, internal/faustjs.org/docs/migrationPath/overview.mdx, internal/legacy.faustjs.org/sidebars.js, packages/faustwp-cli/utils/generatePossibleTypes.ts
Adds a link to migration path when using the `generate` script in legacy project.
1. Run the generate script for the legacy example project:
`npm run generate -w examples/next/getting-started`
2. You should see the message in the console:
=> [MERL-524] Add link to migration doc in cli

internal/legacy.faustjs.org/docusaurus.config.js
Temporarily comments out banner in faustjs site.
=> Commented out deprecation banner

.changeset/healthy-windows-beg.md, packages/faustwp-core/src/client.ts
Fixes: https://github.com/wpengine/faustjs/issues/1082
=> BugFix: Fix Apollo Client Data merge

internal/faustjs.org/docs/next/guides/post-page-previews.mdx, internal/faustjs.org/package-lock.json, internal/faustjs.org/sidebars.js
Documents Post page previews.
Visit `/docs/next/guides/post-page-previews`
=> [MERL-490] Docs: Document Post/Page previews

internal/legacy.faustjs.org/blog/2022-10-26-sprint-21-update.md
=> Sprint 21 blog post

package-lock.json, package.json
Follow up to #1096, removing the `docusaurus` dependency from the root `package.json`.
=> Remove unnecessary `docusaurus` dependency from root `package.json`

.github/workflows/audit-dependencies.yml, audit-ci.jsonc
These changes include a new workflow that will report back the results of "npm audit" using https://github.com/IBM/audit-ci/.
=> [MERL-527] Automate npm audit within CI/CD

internal/legacy.faustjs.org/docusaurus.config.js
=> Add back deprecation banner

internal/faustjs.org/blog/2022-11-09-sprint-22-update.md
Two fixes to syntax in blog post 22- an addition of a parenthesis and a removal of square brackets.
=> Fix parens/bracket emphasis  in blog post

internal/legacy.faustjs.org/docusaurus.config.js
This PR updates the Algolia API keys for `legacy.faustjs.org`
=> Update Algolia settings for legacy.faustjs.org

.changeset/large-eagles-serve.md, internal/faustjs.org/package-lock.json, internal/legacy.faustjs.org/docusaurus.config.js, internal/legacy.faustjs.org/package-lock.json, packages/faustwp-core/src/index.ts
=> Sync `main` <- `canary` for legacy.faustjs.org deploy

internal/legacy.faustjs.org/docusaurus.config.js
=> Fix incorrect API key

.github/PULL_REQUEST_TEMPLATE.md, README.md, internal/legacy.faustjs.org/docusaurus.config.js
=> Fix incorrect API key (#1157) -> `main`

internal/legacy.faustjs.org/src/pages/index.js
Final PR for Algolia search on `legacy.faustjs.org` 😅
=> Update Algolia App ID in CSP

internal/faustjs.org/blog/2022-11-23-sprint-23-update.md
=> Sprint 23 Blog Post

examples/next/faustwp-getting-started/components/SEO/SEO.js
Added note to the jsdoc for imageUrl saying that the path for the image must be an absolute URL.
=> MERL-456: updated jsdoc to require absolute url

internal/faustjs.org/blog/2022-12-07-sprint-24-update.md
=> Sprint 24 blog post

internal/faustjs.org/docs/next/guides/project-walkthrough.mdx
=> Fixes the link to the Getting Started page

.changeset/dirty-beds-cover.md, .changeset/grumpy-windows-provide.md, examples/next/faustwp-getting-started/components/SEO/SEO.js, examples/next/faustwp-getting-started/package.json, examples/next/getting-started/README.md, internal/faustjs.org/blog/2022-12-07-sprint-24-update.md, internal/faustjs.org/docs/going-to-production/deployment.mdx, internal/faustjs.org/docs/next/guides/project-walkthrough.mdx, internal/faustjs.org/docusaurus.config.js, internal/faustjs.org/package-lock.json, internal/faustjs.org/package.json, internal/faustjs.org/sidebars.js, package-lock.json, packages/core/README.md, packages/faustwp-cli/CHANGELOG.md, packages/faustwp-cli/index.ts, packages/faustwp-cli/package.json, packages/faustwp-core/src/components/WordPressTemplate.tsx, packages/faustwp-core/src/getWordPressProps.tsx, packages/faustwp-core/src/index.ts, packages/next/README.md, packages/react/README.md
=> Release blog post

internal/faustjs.org/blog/2022-10-26-sprint-21-update.md
=> [NOJIRA] Fix blog link display

.changeset/dirty-beds-cover.md, .changeset/grumpy-windows-provide.md, examples/next/faustwp-getting-started/components/SEO/SEO.js, examples/next/faustwp-getting-started/package.json, examples/next/getting-started/README.md, internal/faustjs.org/blog/2022-10-26-sprint-21-update.md, internal/faustjs.org/blog/2022-12-07-sprint-24-update.md, internal/faustjs.org/docs/going-to-production/deployment.mdx, internal/faustjs.org/docs/next/guides/project-walkthrough.mdx, internal/faustjs.org/docusaurus.config.js, internal/faustjs.org/package-lock.json, internal/faustjs.org/package.json, internal/faustjs.org/sidebars.js, package-lock.json, packages/core/README.md, packages/faustwp-cli/CHANGELOG.md, packages/faustwp-cli/index.ts, packages/faustwp-cli/package.json, packages/faustwp-core/src/components/WordPressTemplate.tsx, packages/faustwp-core/src/getWordPressProps.tsx, packages/faustwp-core/src/index.ts, packages/next/README.md, packages/react/README.md
=> Deploy blog link fix

.changeset/nervous-wombats-sell.md, .github/workflows/release-packages.yml, plugins/faustwp/CHANGELOG.md, plugins/faustwp/faustwp.php, plugins/faustwp/package.json, plugins/faustwp/readme.txt
These changes support the re-release of our WordPress plugin as we troubleshoot automating that process.
=> Update Changeset Workflow

internal/faustjs.org/blog/2022-12-22-sprint-25-update.md
=> Sprint 25 blog post

internal/faustjs.org/blog/2022-12-22-sprint-25-update.md, internal/faustjs.org/docs/templates.mdx, plugins/faustwp/composer.lock
=> Sync `main`

package-lock.json
JSON5 and encode packages updated with npm audit to satisfy dependabot issues. Also affects @babel/core.
=> MERL-688: Update package-lock.json for json5 dependabot audit

audit-ci.jsonc, internal/faustjs.org/docs/getting-started.mdx, internal/legacy.faustjs.org/docs/next/getting-started.mdx, plugins/faustwp/includes/settings/callbacks.php
Update documentation with frontend site url setting in the Headless Plugin.
=> Updated to add frontend url setting in headless plugin

audit-ci.jsonc, internal/faustjs.org/blog/2022-12-22-sprint-25-update.md, internal/faustjs.org/blog/2023-01-04-faust-update-jan-04-2023.md, internal/faustjs.org/docs/faq.mdx, internal/faustjs.org/docs/getting-started.mdx, internal/faustjs.org/docs/templates.mdx, internal/legacy.faustjs.org/docs/next/getting-started.mdx, package-lock.json, plugins/faustwp/composer.lock, plugins/faustwp/includes/settings/callbacks.php
=> Publish blog post

internal/faustjs.org/blog/2023-01-18-faust-update-jan-18-2023.md
=> NOJIRA Create Jan 18 blog post

internal/faustjs.org/docs/sitemaps.mdx, internal/faustjs.org/sidebars.js
=> [MERL-710] Remove Sitemap page

internal/faustjs.org/package-lock.json, internal/faustjs.org/package.json
=> NOJIRA: Update Docusarus to 2.2.0

internal/faustjs.org/docusaurus.config.js
Adds the Discord link to the Navbar and footer community column.
=> Add discord link to navbar and footer

.github/workflows/e2e-next-example.yml, .github/workflows/e2e-test-plugin.yml, .github/workflows/test-packages.yml
Adds testing for Node v16 and v18 LTS in GA.
=> MERL-135 - Add node version matrix in GA.

.changeset/forty-stingrays-own.md
This changelog is not required. This functionality was never documented in new Faust.
=> Remove changeset

internal/faustjs.org/blog/2021-12-03-upgrading-to-faustwp.md, internal/faustjs.org/blog/2022-07-06-the-future-of-faust.md, internal/faustjs.org/blog/2022-07-20-sprint-14-update.md, internal/faustjs.org/blog/2022-08-03-sprint-15-update.md, internal/faustjs.org/blog/2022-08-16-sprint-16-update.md, internal/faustjs.org/blog/2022-08-31-sprint-17-update.md, internal/faustjs.org/blog/2022-09-14-sprint-18-update.md, internal/faustjs.org/blog/2022-09-30-sprint-19-update.md, internal/faustjs.org/blog/2022-10-12-sprint-20-update.md, internal/faustjs.org/blog/2022-10-26-sprint-21-update.md, internal/faustjs.org/blog/2022-11-09-sprint-22-update.md, internal/faustjs.org/blog/2022-11-23-sprint-23-update.md, internal/faustjs.org/blog/2022-12-07-sprint-24-update.md, internal/faustjs.org/blog/2022-12-22-sprint-25-update.md, internal/faustjs.org/blog/2023-01-04-faust-update-jan-04-2023.md, internal/faustjs.org/blog/2023-01-18-faust-update-jan-18-2023.md
=> NOJIRA - Add authorship to existing blog posts

internal/faustjs.org/package-lock.json, internal/faustjs.org/package.json, internal/legacy.faustjs.org/package-lock.json, internal/legacy.faustjs.org/package.json
=> Nojira update docusaurus

internal/faustjs.org/blog/2023-02-02-faust-update-feb-03-2023.md
=> Feb 2, 2023 blog post

.github/workflows/e2e-test-plugin.yml, internal/faustjs.org/blog/2021-12-03-upgrading-to-faustwp.md, internal/faustjs.org/blog/2022-07-06-the-future-of-faust.md, internal/faustjs.org/blog/2022-07-20-sprint-14-update.md, internal/faustjs.org/blog/2022-08-03-sprint-15-update.md, internal/faustjs.org/blog/2022-08-16-sprint-16-update.md, internal/faustjs.org/blog/2022-08-31-sprint-17-update.md, internal/faustjs.org/blog/2022-09-14-sprint-18-update.md, internal/faustjs.org/blog/2022-09-30-sprint-19-update.md, internal/faustjs.org/blog/2022-10-12-sprint-20-update.md, internal/faustjs.org/blog/2022-10-26-sprint-21-update.md, internal/faustjs.org/blog/2022-11-09-sprint-22-update.md, internal/faustjs.org/blog/2022-11-23-sprint-23-update.md, internal/faustjs.org/blog/2022-12-07-sprint-24-update.md, internal/faustjs.org/blog/2022-12-22-sprint-25-update.md, internal/faustjs.org/blog/2023-01-04-faust-update-jan-04-2023.md, internal/faustjs.org/blog/2023-01-18-faust-update-jan-18-2023.md, internal/faustjs.org/blog/2023-02-02-faust-update-feb-03-2023.md, internal/faustjs.org/docs/apollo.mdx, internal/faustjs.org/package-lock.json, internal/faustjs.org/package.json, internal/legacy.faustjs.org/package-lock.json, internal/legacy.faustjs.org/package.json
=> Deploy blog post and documentation changes

packages/blocks/README.md
Update README file for Blocks Support
Added content to the README for blocks package.
=> MERL-716: README for Blocks

.changeset/dry-melons-talk.md
=> Release locale as patch

internal/faustjs.org/sidebars.js
=> Fix gutenberg menu

internal/faustjs.org/docs/gutenberg/getting-started.mdx, packages/blocks/README.md
Fix paths for documentation for provider and viewer blocks.
=> updated path for blocks viewer and provider

internal/faustjs.org/docs/gutenberg/getting-started.mdx, packages/blocks/README.md
=> Sync canary to main

.changeset/modern-tables-live.md, packages/faustwp-core/src/components/WordPressTemplate.tsx
Fixes issue with HMR not working with wp-templates
1. Start the example project in dev mode.
2. Edit the content of the template in wp-templates
3. The page should refresh so the developer can see the updates on the fly.
=> [MERL-747] Bug: Fix HMR for wp-templates

packages/faustwp-core/src/components/FaustProvider.tsx, packages/faustwp-core/src/components/Toolbar/Toolbar.tsx, packages/faustwp-core/src/components/Toolbar/ToolbarItem.tsx, packages/faustwp-core/src/components/Toolbar/nodes/Edit.tsx
These changes fix linting issues introduced in https://github.com/wpengine/faustjs/pull/1259
Notice that all GitHub jobs are passing on this pull request.
=> Fix Toolbar linting issues

internal/faustjs.org/blog/2023-03-01-faust-update-mar-01-2023.md
=> Mar 1 blog post

internal/faustjs.org/blog/2023-03-01-faust-update-mar-01-2023.md, internal/faustjs.org/docs/guides/custom-toolbar.mdx, internal/faustjs.org/docs/gutenberg/getting-started.mdx, internal/faustjs.org/docs/gutenberg/migration-from-wp-graphql-gutenberg.mdx, internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-third-party.mdx, internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-wordpress-core.mdx, internal/faustjs.org/sidebars.js
=> Sync Canary & Main

internal/faustjs.org/docs/gutenberg/getting-started.mdx, internal/faustjs.org/docs/gutenberg/wp-graphql-content-blocks.mdx
This PR includes small doc updates:
* Fixes missing tick ` in Gutenberg Getting Started guide
* Adds  mention of `object` attribute type in wp-graphql-content-blocks guide.
=> Docs: Small doc updates

package-lock.json, packages/faustwp-core/package.json, packages/faustwp-core/src/components/Toolbar/Toolbar.tsx, packages/faustwp-core/tests/components/Toolbar/Toolbar.test.tsx, packages/faustwp-core/tests/components/Toolbar/ToolbarItem.test.tsx, packages/faustwp-core/tests/components/Toolbar/ToolbarNode.test.tsx, packages/faustwp-core/tests/components/Toolbar/ToolbarSubmenu.test.tsx, packages/faustwp-core/tests/hooks/useLogin.test.tsx, packages/faustwp-core/tests/jest.setup.ts
Adds unit tests for <Toolbar />
Unit tests should all pass.
=> [MERL-697] Tests: Add tests for <Toolbar />

internal/faustjs.org/docs/reference/getWordPressProps.mdx, internal/faustjs.org/sidebars.js
=> getWordPressProps reference doc

.changeset/chatty-pugs-drop.md, internal/faustjs.org/docs/telemetry.mdx, packages/faustwp-cli/utils/marshallTelemetryData.ts
This PR includes `platform` information in the telemetry payload.
It also updates the docs to include this change.
* Make sure CLI package runs.
* Run the example project and check the google analytics console for the platform information in the metrics view.
=> MERL-745: Include Platform info in telemetry payload

internal/faustjs.org/blog/2023-03-15-faust-update-mar-15-2023.md
This PR includes a sprint update for our site blog.
=> Blog update

README.md, internal/faustjs.org/docs/faq.mdx, packages/blocks/README.md, packages/faustwp-cli/README.md, packages/faustwp-core/README.md
These changes remove an outdated project notice and add a new FAQ.
=> Remove outdated notice

.changeset/beige-owls-glow.md, .changeset/honest-pugs-live.md
* Updated language on blocks package breaking change
* Updated bump semver type of plugin release to reflect feature release during a prerelease (patch bump instead of a minor bump)
=> Fix changesets

.github/workflows/nextjs-bundle-analysis.yml
=> Fix bundle workflow

.changeset/lemon-ravens-bow.md
Added changeset for legacy packages to deploy readme updates
=> MERL-807: Add changeset for legacy packages to deploy readme updates

package-lock.json, package.json
This should handle the creation of private package git tags correctly.
Tested locally with this latest version of changesets in the Faust.js repo and the private package git tags were created as expected.
=> Updates changesets CLI version to latest

packages/blocks/src/theme.ts
Create a TypeScript schema type based off of @theodesp's spike document for theme.json support.
=> Create `theme.json` TS type

scripts/stats/.eslintrc.json, scripts/stats/.gitignore, scripts/stats/28day.js, scripts/stats/index.js, scripts/stats/package-lock.json, scripts/stats/package.json
=> NOJIRA Adds 2 scripts for generating WP Engine kpi data

.github/workflows/deploy-plugin.yml
=> Use checkout action on deploy plugin action

.changeset/silver-olives-breathe.md, packages/faustwp-core/src/getWordPressProps.tsx
Bug Fix for https://github.com/wpengine/faustjs/issues/1379
Follow the instructions of the original issue to test a site using `getServerSideProps` on the index page.
=> Bug Fix: Error on client-side navigation to SSR page

.github/workflows/nightly-releases.yml, package-lock.json, package.json
This PR introduces nightly releases of the `canary` branch to NPM.
These releases are ["snapshot releases"](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md) and are not appended to the changelog. As such, once the packages are published to NPM, the resulting changes are not committed back like in the "version packages" PRs.
The releases are named the following: `0.0.0-DATE_AND_TIME_OF_RELEASE` under the `canary` tag in NPM.
This naming is for NPM to properly resolve the most recent version on the given tag. Changesets talks more about this in their docs.
For example:
https://www.npmjs.com/package/@blakewilson/package-c/v/0.0.0-20230501204434?activeTab=versions
The user can then install Faust packages using the `canary` tag:
```
npm install @faustwp/core@canary …
```
=> Create Nightly Releases

internal/faustjs.org/blog/2023-05-01-faust-update-may-1-2023.md
Added a blog post that covers a few key implementations since our last post for the community.
Please read and provide any feedback related to content/grammar/spelling as needed. Thank you!
=> Added May 1st 2023 blog post

.github/workflows/test-plugin.yml
No changeset is required for these changes.
Observe that CI tests are passing
=> Test against additional WordPress versions

.changeset/short-rats-act.md
Adds changeset  for https://github.com/wpengine/faustjs/pull/1426/files
=> Chore: Add changeset for `fromThemeJson`

log.txt, scripts/stats/commit.js, scripts/stats/package-lock.json, scripts/stats/package.json
=> Generate stats for project contributors

scripts/stats/commit.js
=> NOJIRA Exclude Chris Wiegman from external contribution count

.changeset/lazy-donuts-flow.md, .changeset/many-drinks-stare.md
These duplicates somehow snuck into my previous PR.
=> Remove duplicate changesets

.changeset/large-emus-hear.md, .changeset/tall-cougars-sit.md
Adds the missing changeset for the `CoreCode` block.
=> Add changeset for CoreCode

.changeset/calm-peas-rescue.md, .changeset/clever-rice-fetch.md, .changeset/many-pots-love.md, .changeset/slimy-dolphins-tap.md
This PR changes all versions of our packages/plugins to 1.0.0. Some packages may have breaking changes.
=> Add semver changesets

.changeset/clever-rice-fetch.md
=> Fix faustwp/core changeset

.changeset/chatty-brooms-wink.md
=> Finish release by updating to 1.0.1

.changeset/chatty-brooms-wink.md
=> Fix changeset

.github/PULL_REQUEST_TEMPLATE.md
=> Add new Testing task for PRs

scripts/stats/commit.js
This simply updates the exclusions array to include dependabot.
=> NOJIRA Exclude dependabot from committer stats

.github/PULL_REQUEST_TEMPLATE.md, DEVELOPMENT.md
This adds a "changes" checkbox to the PR template with a link to the most appropriate documentation I could find on actually creating the changeset.
=> [NOJIRA] Add changeset message

.changeset/popular-poets-lick.md
=> Update changeset description

scripts/stats/index.js, scripts/stats/package-lock.json, scripts/stats/package.json, scripts/stats/src/contributors.js, scripts/stats/src/downloads.js, scripts/stats/src/raw.js
Cleans up and updates the stats regeneration scripts I built last quarter to make them a bit easier for me to work with going forward.
=> [NOJIRA] Update stats generation

plugins/faustwp/readme.txt
=> NOJIRA Update tested up to version for WordPress 6.3

.github/workflows/test-plugin.yml
- [] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.
Updated CI/CD pipeline for FaustWP to test against  WordPress v6.3.
=> CI/CD: (FaustWP) Test plugin against WP 6.3

package-lock.json, packages/block-editor-utils/package.json, packages/block-editor-utils/src/components/Save.tsx, packages/block-editor-utils/src/registerFaustBlock.ts, packages/block-editor-utils/src/types/index.d.ts, packages/block-editor-utils/tests/components/Save.test.tsx
* Adds default Save function when using `registerFaustBlock`
* Unit tests.
https://github.com/wpengine/faustjs/issues/1522
1. run `npm install`
2. Build the project 
3. cd inside the project folder:
`cd packages/block-editor-utils`
7. Inside the plugin folder run `npm link @faustwp/block-editor-utils ` to add a reference to the package.
8. Rewrite the genenated `index.js` editor script to use the `registerFaustBlock` helper function instead. 
```js
// index.js
import './style.scss';
// import block.json
import metadata from './block.json';
// import Pure React Component
import MyFirstBlock …
```
=> Feat: (registerFaustBlock) Add Save Function

.changeset/proud-walls-clap.md
=> Fix changeset markup

.changeset/quiet-llamas-play.md, .changeset/two-onions-live.md
Added missing changesets from https://github.com/wpengine/faustjs/pull/1544
=> Create changesets for new App Router features

.changeset/many-houses-push.md, package-lock.json, packages/faustwp-cli/src/healthCheck/validateFaustEnvVars.ts, packages/faustwp-cli/src/healthCheck/verifyGraphQLEndpoint.ts, packages/faustwp-cli/tests/healthCheck/validateFaustEnvVars.test.ts, packages/faustwp-cli/tests/healthCheck/verifyGraphQLEndpoint.test.ts
There was a regression in throwing the proper exit codes upon an empty WordPress URL and the GraphQL endpoint not being accessible. This PR fixes the errors by throwing the proper `1` exit code.
Technically, in the two cases (Where a `NEXT_PUBLIC_WORDPRESS_URL` env var doesn't exist or when the GraphQL Endpoint is unresponsive), we are handling the errors and providing the user with a message as to what went wrong. In some contexts, a `0` exit code then could be considered correct. However, since we are using this as a build tool, we want platforms like Atlas, Vercel, etc to know when these things go wrong, so throwing a `1` exit code makes more sense, since these are "blocking" errors and should technically fail a build/deployment.
1. In the `canary` branch, build the packages `npm run …
=> Fix regression in exit codes in Faust CLI

.changeset/small-planets-share.md, package-lock.json, packages/block-editor-utils/jest.config.js, packages/block-editor-utils/package.json, packages/block-editor-utils/src/controls/Range.tsx, packages/block-editor-utils/src/controls/index.ts, packages/block-editor-utils/src/helpers/getControlFields.ts, packages/block-editor-utils/src/types/index.d.ts, packages/block-editor-utils/tests/controls/Range.test.tsx, packages/block-editor-utils/tests/global-mocks.ts, packages/block-editor-utils/tsconfig.json
Adds `RangeField` Control in block-editor-utils package.
https://github.com/wpengine/faustjs/issues/1522
After pulling this branch down, run the following commands in the faustjs monorepo:
1. run `npm install` 
2. run `npm run build` 
3. run `npm run build -w packages/block-editor-utils`
4. run `cd packages/block-editor-utils`
Switch to your testing site's repo.
npx @wordpress/create-block hello-world-block
7. cd to your new block plugin's folder 
8. Inside the `hello-world-block` plugin folder, run `npm link @faustwp/block-editor-utils` to add a reference to the package.
9. Replace …
=> Feat: (block-editor-utils) Add RangeField

.changeset/chilled-teachers-brush.md
Updated bundle size changeset wording.
=> Updated changeset wording for apollo client fix

examples/next/app-router/package.json, package-lock.json
Some deps are missing when using the `npx create-next-app` for the app router example. This PR adds them.
=> Add dev deps for app router example

.changeset/cold-horses-deny.md, packages/faustwp-cli/src/index.ts, packages/faustwp-cli/src/utils/getNextCliArgs.ts, packages/faustwp-cli/src/utils/index.ts, packages/faustwp-cli/tests/utils/getCliArgs.test.ts, packages/faustwp-cli/tests/utils/getNextCliArgs.test.ts
- [ x ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
=> Allow health checks to be skipped via CLI

.changeset/gold-dodos-flash.md, package-lock.json, packages/block-editor-utils/package.json, packages/block-editor-utils/src/components/EditorForm.tsx, packages/block-editor-utils/src/components/InspectorFields.tsx
Updates npm deps to resolve pipeline issues.
=> chore: update npm deps

.changeset/config.json
This PR ignores the block example project from being versioning in the "version packages" PR.
=> Ignore the block example project for versioning

examples/next/block-support/package.json, package-lock.json
* Updates faust in block example project
* Adds block-editor-utils as dependency.
=> Deps: Include @faustwp/block-editor-utils as a dependency in block example.

.changeset/wet-buttons-love.md, plugins/faustwp/includes/settings/callbacks.php, plugins/faustwp/includes/settings/views/headless-settings.php
Updates the settings page to improve the descriptions and documentation links. The old links were redirecting to the links I've added in the PR.
=> Update settings description

package-lock.json, package.json
Fixes https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
=> Axios advisory Fix

package.json
Added missing build script for app router in `release:nightly` workflow. This was missed in https://github.com/wpengine/faustjs/pull/1640
=> Run build in release:nightly workflow

examples/next/block-support/package.json, package-lock.json
Updates block-support example dependencies to latest Next.js v14
=> Chore: Update block-support example dependencies

.changeset/strong-shoes-lay.md
=> chore: add changeset for #1653

.github/workflows/e2e-test-plugin.yml, plugins/faustwp/.docker/Dockerfile, plugins/faustwp/.docker/scripts/init-testing-environment.sh
- Fixes https://github.com/wpengine/faustjs/issues/1695
- Added the missing Init Testing Environment step back to the E2E testing workflow. This step is responsible for executing the init-testing-environment.sh script within the faustwp plugin, ensuring a proper testing environment setup.
- Added Dockerize in the Dockerfile of the faustwp plugin. Dockerize is essential for waiting until the MySQL service is available.
=> CI/CD: Attempt to fix e2e test env

examples/next/app-router/package.json, package-lock.json, package.json, packages/experimental-app-router/package.json, packages/faustwp-core/src/client.ts
Update @apollo/experimental-nextjs-app-support to v0.8.0
1. Cleanup all your node_modules from the examples/next/app-router.
2. Run npm i and npm run build
3. Start the app-router example project. It should works as. expected.
=> Update @apollo/experimental-nextjs-app-support to v0.8.0-NEW

.github/workflows/e2e-next-example.yml, .github/workflows/e2e-next-faustwp-example.yml, .github/workflows/e2e-nightly-build.yml, .github/workflows/test-packages.yml
Fixes syntax errors in workflow files introduced here: https://github.com/wpengine/faustjs/pull/1806
=> chore: fix syntax error in GitHub workflows

packages/faustwp-core/tests/config/index.test.ts
=> Fix `experimentalPlugins` -> `plugins` tests

package-lock.json, packages/experimental-app-router/package.json, packages/experimental-app-router/src/server/routeHandler/index.ts, packages/experimental-app-router/src/server/routeHandler/tokenHandler.ts, packages/experimental-app-router/tests/server/routeHandler/tokenHandler.test.ts
https://github.com/wpengine/faustjs/issues/1833
https://github.com/wpengine/faustjs/issues/1834
=> Bug Fix: Pass Next server to tokenHandler to fix build issues with experimental-app-router

.changeset/hungry-yaks-push.md, packages/faustwp-core/src/config/index.ts
=> Do not require `plugins`, `experimentalPlugins` in the FaustConfig type

DEVELOPMENT.md
This PR updates the development.md guide as of 2024
Closes #1797
=> Docs: Update Development Guide 2024

examples/next/faustwp-getting-started/package.json, package-lock.json
Updates safe packages in the getting started example excluding Next >12.x, React (and related) > 17.x and WordPress Block Library > 7.x
#1856 
Default tests should be sufficient without further changes.
=> Update default packages in example project

.github/workflows/e2e-next-example.yml, .github/workflows/e2e-next-faustwp-example.yml, .github/workflows/e2e-nightly-build.yml, .github/workflows/experimental-app-router.yml, .github/workflows/unit-test-packages.yml
* Adds Node v22 in Github actions.
=> test(gha): include node 22 in github actions pipeline

internal/legacy.faustjs.org/package-lock.json, package-lock.json
Fixes: https://github.com/advisories/GHSA-c7qv-q95q-8v27
=> bump: http-proxy-middleware to 2.0.7
