wpengine/faustjs

- internal/website/docs/guides/custom-post-types.mdx
> docs: (#306) clean up CPT guide

- internal/website/docs/next/reference/handle-404s.mdx
- internal/website/docs/next/reference/ssr-ssg.mdx
> doc: (#309) finishing 404 doc

- examples/react/getting-started/src/pages/category.tsx
- examples/react/getting-started/src/pages/page.tsx
- examples/react/getting-started/src/pages/post.tsx
- examples/react/getting-started/src/pages/preview.tsx
- packages/next/src/client.ts
- packages/react/src/client.ts
This PR resolves #327.
Removed hooks from the `react` package that had a 1-to-1 representation of the GQless `useQuery` hook and refactored the `react/getting-started` example accordingly.
Additionally, the `useGeneralSettings` and `usePages` hooks were removed from the `next` client
> Refactor React Hooks

- internal/website/docs/guides/custom-post-types.mdx
- internal/website/docs/next/getting-started.mdx
- internal/website/docusaurus.config.js
- internal/website/package.json
- internal/website/src/pages/index.js
- package.json
This site is deployed to Atlas into a "Development" environment. We'll keep this branch open for subsequent deployments. Once we're ready to go live we can set a branch for production deployments and map a domain.
resolves #332
> Site development environment set

- plugins/wpe-headless/includes/graphql/callbacks.php
In our wpgql field logic we are registering two of the same field identifier. This PR removes the one associated with ContentNode as templates seem more appropriate for the previous declaration which includes the context in which the post type or model is used. This also applies to `conditionalTags`
Having trouble running tests locally so hoping someone can give a second look that this change doesn't introduce new issues. I anticipate it wont considering most of the usage of these fields are on the app side. 
Steps to reproduce: 
1) Follow getting started guide for building an Atlas app
2) Create WP install fresh and install the required plugins + wpgql
3) See that the duplicate field error when you run a wpqgl query from IDE with debug mode on
Example error from wpgql IDE with debug mode …
> Remove duplicate field registers for templates and conditionalTags

- plugins/wpe-headless/includes/graphql/callbacks.php
In WordPress 5.8 the templates hierarchy filter used by full site editing is null because we are not returning the object in our callback. This PR properly returns the filtered object as WordPress expects fixing Headless Framework for WordPress 5.8 users.
> Return templates object in the template_hierarchy callback

- packages/core/package-lock.json
- packages/core/package.json
- packages/next/package.json
- packages/next/src/getProps.tsx
- packages/react/package.json
Based on #343 and some testing of my own, it appears there is a bug in gqless related to prerendering. A temporary fix is to simply prerender twice. This fix does exactly that. I've tested this and it appears to work with the `next/getting-started` as well as other sites.
> SSG Temporary Fix

- plugins/wpe-headless/readme.txt
- plugins/wpe-headless/wpe-headless.php
This release includes a fix for properly returning the templates hierarchy from the templates hierarchy filter that causes the Headless Framework to crash.
This PR resolves #365
> make: (#365) Increment plugin versions to 0.5.6

- plugins/wpe-headless/includes/settings/views/headless-settings.php
Some links needed new URLs based on latest refactor. Some links pointed to things that no longer exist at all. All fixed in this PR!
> Update outdated WP doc links

- examples/next/getting-started/gqless.config.js
- examples/react/getting-started/gqless.config.js
For the next getting started `require('dotenv').config();` is not enough because it defaults to `.env` for the file rather than `.env.local`. So we need an additional setting of:
```js
require('dotenv').config({
path: '.env.local',
});
```
> fix: setting proper dotenv config

- plugins/wpe-headless/includes/replacement/callbacks.php
fix: make priority really low to happen last so any plugins modifying url happen first and the domain swap happens last.
fixes #390
> fix: polylang url change conflict

- README.md
This PR refactors the existing readme for Faust.js to a more simple approach like Next.js that directs users on how to get started, documentation, contributing, etc.
It can be viewed live here: https://github.com/wpengine/headless-framework/tree/docs-readme
> Create a simple readme for Faust.js

- packages/next/src/client.ts
- packages/react/src/client.ts
This PR resolves #422.
We now check if any revisions exist for the post/page. If they do, that is the most recent preview data for an existing post/page. Otherwise, we display the data from the original post/page query (draft, or new post/page)
> Fix: (#422) Use most recent post/page revision if exists

- plugins/wpe-headless/includes/replacement/callbacks.php
- plugins/wpe-headless/includes/replacement/previewlinks.js
- plugins/wpe-headless/tests/integration/replacement/test-replacement-callbacks.php
This PR fixes the warning found in #354 by adding the `previewlinks.js` file to `load-post-new.php` and `load-post.php` actions, instead of `enqueue_block_editor_assets`.
Something to note: Enqueueing `previewlinks.js` with `wp-edit-post` as a dependency using these new actions causes the ACM editor/fields to not be displayed properly. The following error is consoled:
```js
react-dom.min.js?ver=16.13.1:125 TypeError: Dn.oldEditor.getDefaultSettings is not a function
at index.js?ver=0.5.0:1
at Bh (react-dom.min.js?ver=16.13.1:126)
at Dj (react-dom.min.js?ver=16.13.1:162)
at unstable_runWithPriority (react.min.js?ver=16.13.1:25)
at Da (react-dom.min.js?ver=16.13.1:60)
at xb (react-dom.min.js?ver=16.13.1:162)
at react-dom.min.js?ver=16.13.1:162
at U (react.min.js?ver=16.13.1:16)
at …
```
> fix: (#354) warning on widgets.php due to previewlinks.js

- .npmrc
- DEVELOPMENT.md
- README.md
- package.json
- Updates docs to reflect switch to npm workspaces in place of Learna.
- Workspaces was introduced in npm v7.0.0. I've added an `engines` property and `.npmrc` to show an error during `npm install` if you don't have the proper version. I included a node v16.0.0 requirement there as well, but I don't know how accurate that is.
- Changes some relative URLs that didn't seem to work in GitHub to absolute URLs.
> Update development docs

- CONTRIBUTING.md
When the docs got reorganized, this link was broken.
> Reference correct path for DEVELOPMENT.md

- docs/release-notes.mdx
- package-lock.json
- packages/core/package.json
- packages/next/package.json
- packages/react/package.json
> make: (#495) release `0.11.0`

- plugins/wpe-headless/includes/settings/views/headless-settings.php
> fix: (#500) setting appropriate faust links from the plugin

- .github/workflows/e2e-next-example.yml
- .gitignore
- docs/next/getting-started.mdx
- docs/next/guides/authentication.mdx
- docs/next/guides/post-page-previews.mdx
- docs/tutorial/setup-faustjs.mdx
- examples/next/getting-started/.env.local.sample
- examples/next/getting-started/.env.sample
- examples/next/getting-started/gqty.config.js
- examples/next/getting-started/package.json
- examples/next/getting-started/src/faust.config.js
- package-lock.json
This PR allows users of the `next/getting-started` example to use any naming of their environment files with the help of [`dotenv-flow`](https://www.npmjs.com/package/dotenv-flow).
Also changed the example to use `.env.local` by default instead of `.env`, as this is what Next.js prefers.
Resolves #447
> Use `.env.local` instead of `.env`

- packages/core/src/auth/server/middleware.ts
Remove the existing refresh token upon an unauthorized response from the fetch token endpoint
Resolves #503
> fix: (#503) remove refresh token upon unsuccessful fetch of tokens

- .changeset/fresh-ads-know.md
- packages/core/src/auth/index.ts
- packages/core/src/auth/server/middleware.ts
This PR technically closes #517.
This PR will implement a `logoutHandler` middleware to clear the refresh token from the cookie.
Ideally we'll want a `useLogout` hook as well that can help facilitate this, however, I think we should implement https://github.com/wpengine/faustjs/issues/518#issuecomment-929771017 prior to avoid/reduce any breaking changes.
> Implement `logoutHandler` middleware

- package-lock.json
- package.json
Fixes failed module resolution for `gqty` when running the `next/getting-started` example project from the root of the monorepo.
> chore: include gqty as a monorepo dev dependency

- .changeset/six-dingos-shake.md
- .changeset/weak-sheep-work.md
- docs/next/guides/authentication.mdx
- docs/next/reference/custom-hooks.mdx
- packages/core/src/auth/server/middleware.ts
- packages/core/test/auth/server/middleware.test.ts
- packages/next/src/hooks/index.ts
- packages/next/src/hooks/useAuth.ts
- packages/next/src/hooks/useLogin.ts
Introduced `UseAuthOptions` on the `useAuth` hook that allows a user to specify the `shouldRedirect` property. This property defines if the `useAuth` hook should redirect to the appropriate url when unauthenticated.
```tsx
import { client } from 'client';
export default function Page() {
const { isAuthenticated, authResult } = client.auth.useAuth({
shouldRedirect: false,
});
// Undefined until the authenticated state is determined. Then true/false.
console.log(isAuthenticated);
/**
* The result of the auth request. If the user is authenticated, the result will be "true".
* Otherwise, the authResult will be an object with two keys: "redirect", and "login".
* These values correlate to the "authType" config option for "redirect" and "local" respectively.
*
* @see …
```
> Add option to disable redirect in `useAuth` hook when a user is unauthenticated

- DEVELOPMENT.md
- plugins/wpe-headless/.env.testing.example
- plugins/wpe-headless/docker-compose.yml
- plugins/wpe-headless/tests/acceptance/PostPreviewCest.php
- plugins/wpe-headless/tests/acceptance/SettingsCest.php
Related to #492, this lays some groundwork for further iteration on e2e testing and the plugin's CI/CD pipeline.
- Fixes existing e2e tests
- Updates and simplifies e2e testing instructions
Follow the e2e testing instructions in [DEVELOPMENT.md ](https://github.com/wpengine/faustjs/blob/5399835f48c2f2bdca3c31bc9742de6e13eeb3e2/DEVELOPMENT.md#end-2-end-testing)and verify that the tests run successfully.
> e2e test improvements

- plugins/faustwp/includes/replacement/graphql-callbacks.php
- plugins/faustwp/tests/integration/replacement/test-graphql-callbacks.php
Resolves #541
As mentioned in #541, it appeared we were not doing domain replacement on menu item URLs. Upon investigation, it appears we _are_ performing replacements that should cover menu item URLs, but these replacements were short-circuited by the presence of `generalSettings` in the response data. I believe the intention here was to skip replacements inside of `generalSettings`, as queries for `generalSettings.url` should accurately report the URL of the WordPress instance rather than the front-end application.
With the way GQty assembles queries, it's likely `generalSettings` will be included in most requests. This PR changes the replacement callback to skip `generalSettings` without preventing replacements elsewhere in the response data.
- Unit tests have been added.
1. Before …
> Correct domain replacement for GraphQL fields

- docs/tutorial/dev-env-setup.mdx
Embed the Faust.js walkthrough tutorial video.
> docs: embed Faust.js tutorial walkthrough video

- .changeset/three-crabs-protect.md
- packages/core/src/server/auth/token.ts
- packages/core/test/server/auth/middleware.test.ts
- plugins/faustwp/includes/rest/callbacks.php
When work on the `wp-org` branch began, we decided to remove the `wpac/v1/authorize` endpoint in favor of `faustwp/v1/authorize`. In an effort to reduce the likelihood of errors due to a mismatch between a site's WordPress plugin version and it's front-end packages, this PR reintroduces the `wpac/v1/authorize` endpoint in a deprecated capacity.
It shouldn't matter whether a user updates their packages first or their WordPress plugin first -- their site should not break in either case. Achieving this cross-compatibility requires us to maintain deprecations that cover both cases.
While this PR should cover our immediate needs, I'm hoping to continue working on a more complete solution. Ideally, we could quickly and clearly warn developers about plugin/package incompatibilities (i.e. …
> Deprecate `wpac/v1` api namespace in favor of `faustwp/v1`

- plugins/faustwp/includes/utilities/callbacks.php
While there shouldn't be any fatal conflicts between WPE Headless and FaustWP, running both plugins could lead to some unexpected behavior. We can try to prevent this by deactivating WPE Headless automatically during activation of FaustWP. Props @blakewilson for the idea!
1. Run this PR's copy of FaustWP, but make sure the plugin is deactivated.
2. [Download the latest copy of WPE Headless](https://wp-product-info.wpesvc.net/v1/plugins/wpe-headless?download)
3. Install WPE Headless as a zip and activate.
4. Go to the Plugins page in the WordPress dashboard.
5. Click activate on FaustWP.
6. See that WPE Headless is deactivated.
> Deactivate WPE Headless on FaustWP activation

- DEVELOPMENT.md
@blakewilson A diff seemed easier than review comments on #671.
The main thing I wanted to suggest was in regards to the staging workflow. I was thinking we would just merge the feature branch into `site-dev` locally and push to deploy. The changes would already be under review in the PR that targets `canary`, so we don't need the duplicate PR just to get things to the staging site. This could obviously leave staging in a potentially dirty or conflicted state, but I think that's a limitation of only being able to publish with branch pushes right now.
Everything else looks great!
> Suggestions for git workflow guidelines

- package.json
- scripts/buildPluginReadme.js
- Adds `scripts/buildPluginReadme.js`, which pulls the notes for the latest three versions in CHANGELOG.md into `readme.txt`.
- Runs the script automatically during versioning with `npm run version`.
You can test the script by manually adding a new version section to the plugin's CHANGELOG.md, running `node scripts/buildPluginReadme.js`, and confirming that the changelog section of `readme.txt` is correctly updated.
> Generate readme.txt changelog during versioning

- .github/workflows/e2e-next-example.yml
Fixes the path to the E2E example repo in the Next.js E2E Example Action
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-32
> fix(tests): Fix repo path to E2E Next.js example

- internal/website/blog/2021-12-03-upgrading-to-faustwp.md
Clarifies that plugin settings from WP Engine Headless are preserved during upgrade to FaustWP.
> Add details about plugin settings preservation

- .changeset/cyan-wasps-sell.md
- plugins/faustwp/includes/settings/callbacks.php
- plugins/faustwp/tests/integration/settings/test-functions.php
Adds a link to the plugin's Settings page when viewing the Plugins > Installed Plugins page.
I noticed someone saying they had a hard time finding the settings page and thought this might be helpful.
Verified the link appears and works. Wrote unit test to check for callback.
Added Settings page link to Installed Plugins list.
> feat: add link to Settings page on Installed Plugins list page

- internal/website/docs/next/guides/post-page-previews.mdx
Signed-off-by: theodesp <theo.despoudis@wpengine.com>
The Custom Post Types guid demonstrates now how to create single pages for each custom post type post using the new `usePreviewNode` hook.
Closes #544
* Run the docs locally and observe the new content.
See commit changes
> doc(post-page-previews.mdx) Update docs using `usePreviewNode` hook

- plugins/faustwp/includes/settings/callbacks.php
Small update to the URL we use for the settings link on the plugin page. The former one got you to the right screen, but wasn't recognized and highlighted in the sidebar. We use `options-general.php?page=faustwp-settings` everywhere else, so this just keeps us consistent and restores the menu item's active state in the sidebar.
> fix: correct admin url for plugin settings link

- .github/actions/post-release/index.js
- .github/workflows/post-release.yml
Creates a manually dispatched workflow for testing a job that will automatically merge `canary` into `main` after a Changesets release.
Currently there is no connection between this workflow and the actual Changesets workflow. I've simulated the outputs we get from Changesets for now. If everything works as expected in this simulation, the next step would be to move the `merge_to_main` job into the `release-packages.yml` workflow and hook up the outputs/inputs there.
I've run as much of this as I can locally with `act`, but it needs to be in GitHub to fully test the merge behavior. More specifically, it needs to be on `canary` since the `workflow_dispatch` event I'm using to test can only be triggered from the default branch. The job is currently configured to merge a temporary …
> Add simulated workflow for post release tasks

- examples/next/getting-started/src/pages/preview.tsx
Replace the use of `usePreview` in the starter with the new `usePreviewNode` hook
> 🔨 refactor(examples): use `usePreviewNode`

- .changeset/cool-bikes-grab.md
- packages/core/src/server/auth/middleware.ts
Currently refresh tokens that have been expired are not being properly invalidated and unset due to a bug. The logic is correct, however, it is in a conditional that it should not be in. This PR brings that logic outside of the conditional to properly invalidate the refresh token.
[Video demonstration of the bug](https://www.youtube.com/watch?v=ApqcCDfqaFg) (love this idea @jasonbahl)
1. Clone Faust and create a page called `auth-content.tsx` with the following content:
```tsx
import { client } from 'client';
export default function Page() {
const { isAuthenticated } = client.auth.useAuth();
return <div>My Page</div>;
}
```
2. On line 128 of `plugins/faustwp/includes/rest/callbacks.php`, set `$refresh_token_expiration` to some thing very short, like `5`.
3. Start the dev server running …
> Properly invalidate refresh token upon expiration

- internal/website/docs/next/reference/faust-provider.mdx
- internal/website/sidebars.js
Create a reference doc for the `<FaustProvider>` component.
Staging Site URL: https://hcixzyt38dn5ak04xxcqc36lf.js.wpenginepowered.com/docs/next/reference/faust-provider
> 📝 docs(provider): Ref docs for FaustProvider

- examples/next/getting-started/package.json
Since Faust.js uses ES Modules, Node 12 will not work as intended. Specifying a Node version greater than 14 should help fix this.
> 🔨 refactor(examples): Enforce Node Engine

- internal/website/docusaurus.config.js
- internal/website/src/pages/index.js
Add [Algolia DocSearch](https://docsearch.algolia.com/) to the docs site.
https://hcixzyt38dn5ak04xxcqc36lf.js.wpenginepowered.com/
> Add algolia search

- .changeset/funny-cycles-cry.md
- plugins/faustwp/includes/graphql/callbacks.php
Now that we are using Next.js pages for routing, conditionalTags are no longer needed.
> Deprecate template conditionals

- examples/next/getting-started/package.json
Added missing type dependencies as noted in https://github.com/vercel/next.js/blob/canary/examples/with-typescript/package.json
None
N/A
N/A
N/A
N/A
> Add missing type dependencies

- .github/workflows/sync-example-to-template.yml
This PR sets up a workflow to sync the example project (`examples/next/getting-started`) to the Atlas template for User Portal ([wpengine/faust-atlas-hello-world](https://github.com/wpengine/faust-atlas-hello-world)) when there are changes to `examples/next/getting-started` in the `main` branch of the `wpengine/faustjs` repo.
In order to allow the `wpengine/faustjs` repo to make commits in `wpengine/faust-atlas-hello-world`, we would need to either generate a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) (PAT), or use [deploy keys](https://docs.github.com/en/developers/overview/managing-deploy-keys), as the `GITHUB_TOKEN` env var that is loaded into GitHub Actions only has permissions for the repo …
> Sync `examples/next/getting-started` to Atlas Template

- .github/workflows/sync-example-to-template.yml
The Atlas template sync workflow has a bug where it will not properly sync dot files, since the `mv` command with wildcard glob doesn't recognize hidden files. This PR addresses this by using `rsync` instead.
> 🐞 fix(ci): Properly sync dot files for Atlas template

- internal/website/docs/next/guides/modifying-graphql-request.mdx
- internal/website/sidebars.js
Create a basic guide to illustrate how to intercept the GraphQL request in Faust.js before it is sent to WordPress. This covers the cases in which a user may want to add headers or other info to the request.
> 📝 docs(guide): Modifying GraphQL Request

- internal/website/docs/next/guides/authentication.mdx
- internal/website/docs/next/guides/custom-post-types.mdx
- internal/website/docs/next/guides/fetching-data.mdx
- internal/website/docs/next/guides/handle-404s.mdx
- internal/website/docs/next/guides/post-page-previews.mdx
- internal/website/docs/next/guides/ssr-ssg.mdx
- internal/website/docs/next/reference/api-router.mdx
- internal/website/docs/next/reference/expected-url-params.mdx
- internal/website/docs/next/reference/faust-provider.mdx
- internal/website/docs/next/reference/hooks/useAuth.mdx
- internal/website/docs/next/reference/hooks/useLogin.mdx
- internal/website/docs/next/reference/hooks/useLogout.mdx
- internal/website/docs/next/reference/hooks/usePage.mdx
- internal/website/docs/next/reference/hooks/usePost.mdx
- internal/website/docs/next/reference/hooks/usePosts.mdx
- internal/website/docs/next/reference/hooks/usePreview.mdx
- internal/website/docs/next/reference/hooks/usePreviewNode.mdx
- internal/website/docs/tutorial/basic-headless-site.mdx
- internal/website/docs/tutorial/first-react-component.mdx
- internal/website/docs/tutorial/querying-data.mdx
- internal/website/docs/tutorial/setup-faustjs.mdx
- internal/website/src/mdx/base-url-notice.mdx
This PR standardizes the import path in the docs to use the project root, and explains that this should be configured in `tsconfig.json`. Guides and ref docs also now display a notice saying:
> This doc assumes you're storing your pages/styles/etc. in a directory called `src`, and you have the `baseUrl` option set to `src` in your `tsconfig.json` for import modules from the root.
To be more clear on how imports are handled.
1. Added Base Url notice to all docs that use imports from the root
2. Standardized the import paths to use no relative import paths and instead import from the root. e.g. `import 'styles/globals.css'` instead of `import '../styles/globals.css'`
3. Added a [section](https://hcixzyt38dn5ak04xxcqc36lf.js.wpenginepowered.com/docs/tutorial/basic-headless-site#setup-typescri …
> Standardize the import path in the docs

- examples/next/getting-started/package.json
- examples/next/getting-started/src/client/schema.generated.ts
- package-lock.json
- package.json
- packages/core/package.json
- packages/next/package.json
- packages/react/package.json
- Updates `@types/node` to latest version
- Updates `sharp` to latest version
- Removes outdated `@gqty/cli` as a devDependency from `@faustjs/core` since we don't generate schemas from there.
- Updates `@gqty/cli` in the example project.
- Includes a new schema from a blank WP site to reflect the updated output from `gqty generate`
> Updates dependencies

- internal/website/docs/next/guides/logging-queries.mdx
If we run the example code in the doc [Logging Queries](https://faustjs.org/docs/next/guides/logging-queries), we get this error
```typescript
ReferenceError: logQueries is not defined
22 | 
23 | if (process.env.NODE_ENV === 'development') {
> 24 |   logQueries(client);
|  ^
25 | }
26 | 
27 | export function serverClient(req: IncomingMessage) {
ReferenceError: logQueries is not defined
at eval (webpack-internal:///./src/client/index.ts:22:3)
at Object../src/client/index.ts (/var/www/next-nefrock-web/.next/server/pages/_app.js:22:1)
at __webpack_require__ (/var/www/next-nefrock-web/.next/server/webpack-runtime.js:33:42)
at eval (webpack-internal:///./src/pages/_app.tsx:13:64)
at Object../src/pages/_app.tsx (/var/www/next-nefrock-web/.next/server/pages/_app.js:55:1)
at __webpack_require__ …
```
> Fix a minor import issue in the docs

- .changeset/modern-llamas-shop.md
- packages/core/src/server/router/index.ts
- packages/core/test/server/router/router.test.ts
- packages/next/src/config/withFaust.ts
- packages/next/test/withFaust.test.ts
I wasn't able to find a single regex that works both when `trailingSlash` is enabled and when it's disabled, but we _can_ check the config and modify the regex appropriately. If `trailingSlash` is enabled, we expect the `/` at the end of the `/preview` `source` path. We also add it to the `destination` to avoid triggering another `trailingSlash` redirect.
Once that was corrected, I still had issues previewing. The `apiRouter` was returning a 404 on the `auth/token/` endpoint because of the trailing slash, hence the added `trimEnd()`.
Jest tests were added. I'd like to cover this in an e2e test as well, but booting a totally separate front-end with a different next.config.js just to test for `trailingSlash` seemed excessive. Maybe one day we'll have a way to easily swap configs in our e2e …
> Fix previews when `trailingSlash` is enabled in Next.js config

- packages/core/src/auth/client/accessToken.ts
- packages/core/test/auth/client/accessToken.test.ts
Currently, the access token is refreshed on a `setInterval`, globally polluting the module scope. This PR explicitly refreshes the access token by setting a timer to be invoked 60 seconds before the existing token expires.
Not only will this be more efficient, but will improve the testing experience as well as a timer is not being invoked globally when importing the `@faustjs` packages.
Tests have been provided.
Manual testing:
1. Add the following before the `setRefreshTimer` statement of `setAccessTokenRefreshTimer()`:
```ts
const expiresDate = new Date(
new Date().getTime() + secondsUntilExpiration * 1000,
).toString();
const refreshDate = new Date(
new Date().getTime() + secondsUntilRefresh * 1000,
).toString();
console.log(
`Access token expires at ${expiresDate}, access token will …
```
> Explicitly refresh access token

- .changeset/sixty-fishes-nail.md
- plugins/faustwp/includes/admin-menus/callbacks.php
- plugins/faustwp/tests/integration/admin-menus/test-callbacks.php
Fixes branch name from #792 
Disables the site editor from the sidebar, top bar, and direct access when the `Disable WordPress theme admin pages` setting is checked.
Writing good automated tests for this was difficult because the items that show up under Appearance or in the admin bar vary depending on which theme is active. Checking for presence/absence of specific menu items would be unreliable. For example, our test environment currently runs Twenty Twenty-one, which doesn't enable the site editor at all. If I added a test to verify that `site-editor` is not in the Appearance menu, it would pass both before and after these changes; with or without themes enabled. While switching themes during the test could be an option to explore in the future, that level of test expansion seemed out …
> Disable the site editor when themes are disabled

- .changeset/cyan-apples-work.md
- plugins/faustwp/includes/settings/callbacks.php
- plugins/faustwp/tests/acceptance/SettingsCest.php
- plugins/faustwp/tests/integration/settings/test-callbacks.php
This change sanitizes the `frontend_uri` setting from having a trailing slash `/` .
A user can attempt to save a valid URL with a trailing slash however it will be removed before the value is saved to the database. This change also accounts for those sites that already have a trailing slash in their database.
1. Attempt to save a valid URL containing a trailing slash as the `frontend_uri`. _e.g._ `http://example.org/`
2. Save Settings
3. Verify trailing slash did not save to DB
WP-CLI: `wp option get faustwp_settings`
> Remove trailing slash

- .changeset/wet-dots-pretend.md
- plugins/faustwp/composer.json
- plugins/faustwp/includes/replacement/callbacks.php
- plugins/faustwp/includes/replacement/functions.php
- plugins/faustwp/tests/integration/replacement/test-replacement-callbacks.php
- plugins/faustwp/tests/integration/replacement/test-replacement-functions.php
These changes normalize the sitemap URLs to always have the WordPress Home URL as the base, regardless of any FaustWP setting.
Since this is essentially a reversal of the plugin filtering `post_link`, this normalization is only needed in the following sitemap providers
- posts
- taxonomies
This also fixes the issue where posts & taxonomies were not showing up in the sitemap Yoast generates due to Yoast intentionally filtering out external sitemap entries.
1. Setup a local WordPress install with both FaustWP & Yoast (wordpress-seo) activated.
2. Visit settings -> permalinks & save changes in order to flush WordPress rewrite rules.
3. Create a few test posts.
4. Visit /sitemap.xml to view the sitemap index & go to the post sitemap.
5. You should now see all posts with the current WordPress …
> Have Next handle sitemap URL replacement

- examples/next/getting-started/src/pages/_document.tsx
- examples/next/getting-started/src/scss/_variables.scss
- internal/website/src/css/custom.css
These changes remove the usage of Google Fonts in favor of system fonts.
1. Spin up example site - `npm run dev`
2. Open dev tools and check that computed fonts are showing system fonts
```css
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
```
^ System font-stack taken from GitHub
3. Spin up docs site - `npm run docs`
4. Open dev tools and check that computed fonts are showing system fonts
> System fonts

- internal/website/docs/next/reference/is404.mdx
- internal/website/sidebars.js
We already had a pretty [thorough guide](https://faustjs.org/docs/next/guides/handle-404s), so I kept this lean and linked out where I could. Is there anything missing that would make this more useful?
> Add ref doc for is404

- internal/website/README.md
Replace `yarn` commands in website readme with `npm` commands.
n/a
n/a
n/a
n/a
n/a
> Replace yarn commands in readme with npm commands

- internal/website/docs/next/reference/handle-sitemap-requests.mdx
- internal/website/sidebars.js
Creates a reference doc detailing the usage/options of `handleSitemapRequests`
N/A
* Added "Using handleSitemapRequests" ref doc
* Included in the sidebar under "Usage with Next.js -> Reference -> Using handleSitemapRequests"
Deploying...
> Create `handleSitemapRequests` ref doc

- .changeset/selfish-shrimps-care.md
- internal/website/docs/core/reference/config.mdx
- packages/core/src/config/config.ts
This PR adds a @deprecated flag on the core config `applyRequestContext` referencing the correct way to use this function in the [getClient](http://localhost:3000/docs/next/guides/modifying-the-graphql-request) guide.
1. Run the docs site
2. Navigate to the `/docs/core/reference/config` page
3. Read through the docs
The following pages we modified:
* `/docs/core/reference/config`
> [MERL-235] Deprecate `applyRequestContext`

- .changeset/light-ligers-join.md
- plugins/faustwp/includes/replacement/callbacks.php
- plugins/faustwp/tests/integration/replacement/test-replacement-callbacks.php
WordPress preview links include the `preview=true` query param by default. We rely on this query param to identify and handle preview requests on Faust.js frontends. Any WP plugin ([PublishPress](https://wordpress.org/plugins/publishpress/) is a known example) could potentially remove `preview=true`, causing previews to fail.
This PR explicitly adds `preview=true` to all preview links in case it was removed by another plugin.
Integration test is included.
> Explicitly set `preview=true` in preview links

- .gitattributes
This adds a basic .gitattributes which allows us to specify the files and paths attributes that should be used by git when performing specific git actions.
- [gitattributes Documentation](https://git-scm.com/docs/gitattributes)
> Add basic .gitattributes

- .changeset/old-rice-speak.md
- plugins/faustwp/composer.json
- plugins/faustwp/includes/settings/functions.php
- plugins/faustwp/includes/utilities/callbacks.php
- plugins/faustwp/phpunit-multisite.xml.dist
- plugins/faustwp/tests/integration/settings/test-functions.php
This change handles the following multisite scenarios
- Default settings are properly applied to all sites when plugin is activated, both individual and network activations.
- Default settings are properly applied to newly created sites within a multisite network.
1. Create a new WordPress multisite in Local. (Subdomains/subdirectories does not matter)
2. Create 2 additional sites. Call them whatever you want.
3. Going back to Local, slick "SYNC MULTISITE DOMAINS TO HOSTS FILE".
4. Install FaustWP & network activate.
5. Go to Site 1 -> Settings -> Headless to view FaustWP settings.
6. All default settings should be there.
7. Go to Site 2 -> Settings -> Headless to view FaustWP settings.
9. All default settings should be there.
10. With the plugin still active, create another site (Site 3) …
> MERL-247 multisite default settings

- sonar-project.properties
SonarQube scans run on PRs and also on merge to `canary`. The `sonar.newCode.referenceBranch` [setting causes the scan to fail](https://github.com/wpengine/faustjs/runs/6408851207?check_suite_focus=true) on merge to `canary`. This removes the scanner parameter so that the [default Project level settings](https://docs.sonarqube.org/latest/project-administration/new-code-period/) are used instead.
> Fix SonarQube scan on canary

- internal/website/docs/tutorial/basic-headless-site.mdx
This PR adds a tip to the Faust.js getting started guide mentioning
how Local Atlas extension can help saving some steps in the process.
MERL-277
1. Navigate to the `/docs/tutorial/basic-headless-site` section of the docs.
2. Observe the tooltip section pertaining information about  Local Atlas Extension
> [MERL-277] docs(tip): Adds Local Atlas Extension Links to getting started section

- .changeset/kind-radios-cough.md
- plugins/faustwp/includes/replacement/graphql-callbacks.php
This fixes an issue with using wp-graphql in a WordPress multisite using subdirectories where the individual site subdirectory is included with the menu path.
1. Create a local subdirectory multisite.
2. Add a second site in the network under `site-2`.
3. Install & network activate faustwp & wp-graphql.
4. Under site-2's headless settings, enter `http://localhost:3000` for the `frontend_uri`.
5. Run the following inside of site-2's GraphiQL.
```graphql
query MyQuery {
generalSettings {
url
}
menuItems(where: {location: PRIMARY}) {
nodes {
label
url
path
}
}
menus(where: {location: PRIMARY}) {
nodes {
menuItems {
nodes {
label
url
path
}
}
}
}
}
```
6. `site-2` should no longer present within `url` or `path`. 
**Before**
**After**
> Remove multisite subdirectory from path

- .changeset/proud-coats-hang.md
- plugins/faustwp/includes/deny-public-access/callbacks.php
When loading the full site editor, it makes a request to the site's frontend to determine what template to load. The request fails when public route redirects are enabled and causes White Screen of Death. This PR allows that request to skip redirection which allows the site editor to load successfully.
On WP 5.9.3:
1. Go to Settings -> Headless
2. Uncheck "Disable WordPress theme admin pages" and make sure "Enable public route redirects" is checked. Save.
3. Go to Appearance -> Editor (if you don't see Editor, go activate the TwentyTwentyTwo theme and try again)
4. See that the editor fails to load
5. Return to the dashboard
6. Checkout this PR
7. Go to Appearance -> Editor
8. See that the editor loads
> fix: loading full site editor when public route redirects enabled

- .changeset/odd-buses-mate.md
- plugins/faustwp/includes/replacement/callbacks.php
- plugins/faustwp/tests/integration/replacement/test-replacement-callbacks.php
When using Faust within a multisite setup with subdirectories, the preview links for pages still contain the subdirectory of the site. We will need to filter on [page_link](https://developer.wordpress.org/reference/hooks/page_link/) in addition to [post_link](https://developer.wordpress.org/reference/hooks/post_link/) within FaustWP.
> Filter page_link in addition to post_link

- .github/workflows/e2e-test-plugin.yml
- .github/workflows/test-plugin.yml
- DEVELOPMENT.md
- plugins/faustwp/.distignore
- plugins/faustwp/.docker/Dockerfile
- plugins/faustwp/.docker/scripts/init-testing-environment.sh
- plugins/faustwp/.gitignore
- plugins/faustwp/.zipignore
- plugins/faustwp/composer.json
- plugins/faustwp/composer.lock
- plugins/faustwp/docker-compose.yml
- plugins/faustwp/phpunit-multisite.xml.dist
- plugins/faustwp/phpunit.xml.dist
This PR adds a flag when running the `init-testing-environment.sh` to enable coverage reporting via PCOV. It also updates the `DEVELOPMENT.md` guide to describe the way for this to happen. Once enabled the report is stored within the docker container folder `/var/www/html/wp-content/plugins/faustwp/coverage`.
**Note**: Currently the coverage report is saved locally and  is not send to a CodeClimate.
MERL-315
1. Follow the instructions for setting up the environment for running the WP Unit tests.
Once the containers are up, set up the test framework. If you want to enable code coverage reporting, make sure you provide the `COVERAGE=1` environment variable as a parameter:
```
docker-compose exec -e COVERAGE=1 wordpress init-testing-environment.sh
``` 
Then run the tests as usual:
``` …
```
> [MERL-315] - Code Coverage FaustWP

- examples/next/faust-nx/package.json
- packages/faust-nx/package.json
Add the `private` property to respective `package.json` files so FaustNX packages are not published.
> Add private flag so faustnx packages are not published

- internal/website/docs/next/guides/sitemaps.mdx
Imports the `handleSitemapRequests` sitemap helper function from the submodule `@faustjs/next/middleware` for proper tree shaking in the Next.js edge/middleware runtime.
> Docs: Import `handleSitemapRequests` from submodule

- .changeset/sixty-fans-cough.md
- packages/core/tsconfig-cjs.json
- packages/core/tsconfig.json
- packages/next/tsconfig-cjs.json
- packages/next/tsconfig.json
- packages/react/tsconfig-cjs.json
- packages/react/tsconfig.json
This change adds support for iOS 12 & 13 and fixes https://github.com/wpengine/faustjs/issues/903 by lowering the [target value](https://www.typescriptlang.org/tsconfig#target) in each package's TSConfig.
>The special ESNext value refers to the highest version your version of TypeScript supports. This setting should be used with caution, since it doesn’t mean the same thing between different TypeScript versions and can make upgrades less predictable.
In order to test this on macOS, XCode should be installed with iOS 13.0 downloaded for the simulator. This likely will need to be downloaded which could take some time. https://developer.apple.com/forums/thread/110911
**Before**
**After**
> Add support for iOS 12 & 13

- internal/website/blog/2022-07-06-the-future-of-faust.md
Adds a fresh blog post to start making use of our blog to help keep users informed on what is going on with Faust.
> Add Catch-up blog post

- .changeset/long-suits-film.md
- plugins/faustwp/.distignore
This change excludes `phpunit-multisite.xml.dist` from the zip for WordPress.org.
> Clean up WP.org zip

- examples/next/faust-nx/package.json
- internal/website/blog/2022-07-06-the-future-of-faust.md
- package-lock.json
- package.json
- packages/faust-nx-cli/LICENSE
- packages/faust-nx-cli/index.ts
- packages/faust-nx-cli/package.json
- packages/faust-nx-cli/tsconfig.json
- packages/faust-nx-cli/utils/getCliArgs.ts
- packages/faust-nx-cli/utils/index.ts
- packages/faust-nx-cli/utils/log.ts
- packages/faust-nx-cli/utils/marshallTelemetryData.ts
- packages/faust-nx-cli/utils/promptUserForTelemetryPref.ts
- packages/faust-nx-cli/utils/requestWPTelemetryData.ts
- packages/faust-nx-cli/utils/sendTelemetryData.ts
- packages/faust-nx-cli/utils/validateFaustNXEnvVars.ts
- packages/faust-nx/package.json
The `faustnx` CLI will allow us to implement telemetry, and better position us in the future for other features that require our input before the `next` CLI runs.
This PR introduces a `faustnx` CLI that acts as a pass through to the `next` CLI, however, with our own telemetry that runs prior to the `next` CLI.
When running the `faustnx` CLI for the first time, you are asked if you would like to enroll in FaustNX Telemetry. By responding with either `true` or `false`, your preferences are then saved to your local machine (`~/.config/configstore/faustnx.json` on Mac) as a JSON file:
```jsonc
{
telemetry: {
notifiedAt: '12345', // timestamp the user was first notified about FaustNX telemetry
anonymousId: '0000-0000-0000', // An anonymous v4 UUID for GA
enabled: true // Either true or false …
```
> FaustNX CLI POC

- plugins/faustwp/includes/rest/callbacks.php
- plugins/faustwp/tests/acceptance/TelemetryCest.php
Use the `POST` method for telemetry endpoint as `GET` requests could be cached.
> Use `GET` method in Telemetry Rest endpoint

- examples/next/faust-nx/faustnx.config.js
- examples/next/faust-nx/pages/[...wordpressNode].tsx
- packages/faust-nx/components/WordPressTemplate.tsx
- packages/faust-nx/config/index.ts
- packages/faust-nx/getWordPressProps.tsx
- packages/faust-nx/index.ts
- packages/faust-nx/package.json
Creates a basic config getter/setter. This will be required for auth with the `client` config.
1. Run `npm run build -w faust-nx` from the monorepo root
2. Run `npm run dev -w faust-nx-getting-started` from the monorepo root
3. Ensure pages and posts are still rendered from the template hierarchy
4. Remove the `templates` from `faustnx.config.js` and ensure an error appears
> Setup FaustNX config getter/setter

- packages/core/src/auth/client/accessToken.ts
- packages/core/src/utils/assert.ts
This PR converts some ESLint `eslint-disable-next-line` comments to inline with `eslint-disable-line` to avoid the comments being picked up by the interpreter.
> Move ESLint next line comment to same line

- internal/website/docs/next/reference/with-faust.mdx
When using the custom `previewDestination` the section in the docs does not mention that we need to add a relevant next.js page with the same name. This would cause 404 issues.
[MERL-409]
Add small note within `/docs/next/reference/with-faust` regarding `previewDestination` paths
[MERL-409]: https://wpengine.atlassian.net/browse/MERL-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MERL-409] Add note for custom `previewDestination` path

- packages/faust-nx/src/getTemplate.ts
- packages/faust-nx/src/getWordPressProps.tsx
This PR introduces two filters for the plugin system:
This filter allows a plugin to mutate the returned possible templates list to resolve a template. It can be used like:
```js
class HelloWorld {
apply({addFilter}) {
addFilter('possibleTemplatesList', 'faust-nx', (possibleTemplates, ctx) => {
return [...possibleTemplates, 'new-template']
})
}
}
```
This filter allows a plugin to mutate the returned seed query document node. We leave the implementation on how they'll mutate the seed query document node up to the user, but we should consider providing utility functions in the callback `ctx` for merging our seed query `DocumentNode` with a user provided one. It can be used like:
```js
class HelloWorld {
apply({addFilter}) {
addFilter('seedQueryDocumentNode', 'faust-nx', (seedQuery, ctx) => …
```
> Setup `possibleTemplatesList` and `seedQueryDocumentNode` filters

- packages/faust-nx/src/hooks/index.ts
- packages/faust-nx/tests/config/index.test.ts
This PR introduces some tests for the plugin system. We're now checking that:
* Plugins that are instantiated in the `experimentalPlugins` config property have their `apply` methods called
* Plugins that do not have an `apply` method fail silently when specified in the `experimentalPlugins` config property
* The lack of the `experimentalPlugins` property does not introduce any adverse effects
> Introduce tests for plugin system

- examples/next/faust-nx/pages/sample-page.tsx
- packages/faust-nx/src/getProps.ts
- packages/faust-nx/src/index.ts
This PR adds an example of how we can support Next.js file based pages in faustNX. It introduces two familiar helper functions:
* `getNextStaticProps`: Used within the `getStaticProps`
* `getNextServerSideProps`: Used within the `getNextServerSideProps`
1. Build the project
2. Create a new page named `sample-page` in WordPress
3. Navigate to the `/sample-page` path in Faust.js
4. Check that the title is populated from the `sample-page` page.
> [MERL-376] Add POC example of file based pages

- examples/next/faust-nx/package.json
- package.json
- packages/faust-nx-cli/LICENSE
- packages/faust-nx-cli/index.ts
- packages/faust-nx-cli/package.json
- packages/faust-nx-cli/tsconfig.json
- packages/faust-nx-cli/utils/getCliArgs.ts
- packages/faust-nx-cli/utils/index.ts
- packages/faust-nx-cli/utils/log.ts
- packages/faust-nx-cli/utils/validateFaustNXEnvVars.ts
This PR extracts the faustnx CLI that acts as a pass through to the next CLI as previously delivered in https://github.com/wpengine/faustjs/tree/MERL-171-telemetry
https://wpengine.atlassian.net/browse/MERL-425
1. Checkout  the branch
2. Run `npm run build -w faust-nx` from the monorepo root
3. Run `npm run build -w faust-nx-cli` from the monorepo root
4. Run `npm i` from the monorepo root
5. Run `npm run dev -w faust-nx-getting-started` to start the FaustNX example app in dev mode
You should also check that the following scripts work as expected:
`npm run build -w faust-nx-getting-started`
`npm run start -w faust-nx-getting-started`
> [MERL-425] Extracted faust-nx-cli from telemetry

- .github/workflows/test-packages.yml
- packages/next/src/server/getProps.tsx
This PR sets the test packages action to use version `16` of Node, which it was previously using 16 and 18 (which we don't support).
Additionally, this PR addresses a small TS issue that was causing tests to fail.
> Use node 16 in actions

- internal/website/package-lock.json
This branch addresses the dependabot ticket 985 
[chore(deps): bump terser from 5.10.0 to 5.15.0 in /internal/website](https://github.com/wpengine/faustjs/pull/985)
- #985
> Updated terser in website to 5.15

- package-lock.json
- packages/faust-nx/package.json
- packages/faust-nx/src/config/index.ts
This PR fixes a few broken tests appeared to be introduced in Jest 28
1. Locally, run `npm run test` from `canary` and notice the failing tests
2. Checkout the `nojira-fix-tests` branch
3. Run `npm run test` and notice the tests succeed
> Fix broken tests: Normalize config and require jest-environment-jsdom dep

- examples/next/faust-nx/wp-templates/archive.tsx
- examples/next/faust-nx/wp-templates/page.tsx
- examples/next/faust-nx/wp-templates/single.tsx
- packages/faust-nx/src/components/WordPressTemplate.tsx
- packages/faust-nx/src/getTemplate.ts
- packages/faust-nx/src/getWordPressProps.tsx
This PR refactors the  current `wp-templates` to adopt a conventional way to access the `query` and `variables` from the component itself instead of individual exports.
https://wpengine.atlassian.net/browse/MERL-436
1. Smoke test the wp-templates by previewing a page and a post
> [MERL-436] refactor: Change signature of wp-template components

- .github/workflows/e2e-next-example.yml
- .github/workflows/e2e-test-plugin.yml
- .github/workflows/lint-packages.yml
- .github/workflows/lint-plugin.yml
- .github/workflows/sonarqube-scan.yml
- .github/workflows/test-packages.yml
- .github/workflows/test-plugin.yml
- DEVELOPMENT.md
These changes prevent the project's GitHub workflows from running against markdown files, and can be seen working in [this test pull request](https://github.com/wpengine/faustjs/pull/995). Notice that only the changeset-bot has posted with no coverage reports.
> Prevent tests from running against docs

- package-lock.json
- packages/core/package.json
- packages/faust-nx/package.json
- packages/next/package.json
- packages/react/package.json
These proposed changes ensure that our CI/CD actions are using the jest version defined by the project. This is in an effort to clear the jest related issues with #986
> Use jest version defined by project

- .github/workflows/release-packages.yml
This pr removes the `rm package-lock.json` step from the release packages action as it was not removed in #1013
> Remove the `rm package-lock.json` step from the release packages action

- packages/core/package.json
- packages/next/package.json
- packages/react/package.json
When faust-nx was added to this project, `npx` was removed from the `test:coverage:ci` script as it was causing CI/CD issues.
Since faust-nx has been removed from this project, builds are failing as jest cannot be found.
These changes add `npx` back which resolves the error.
> Fix missing jest build issue

- .github/workflows/e2e-next-example.yml
- .github/workflows/e2e-test-plugin.yml
- .github/workflows/lint-packages.yml
- .github/workflows/release-packages.yml
- .github/workflows/test-packages.yml
These changes update the project's GitHub actions to use `npm ci` [as recommended by npmjs.org](https://docs.npmjs.com/cli/v8/commands/npm-ci) for usage within continuous integration environments.
> Use npm ci

- .changeset/angry-cameras-stare.md
This PR adds the appropriate changeset that was left out when fixing the `Type '{}' is missing...` bug in #1013 ([`packages/next/src/server/getProps.tsx`](https://github.com/wpengine/faustjs/pull/1013/files#diff-89624db982206bbb7e486fe2bf3ab218bde8d45c7749fb44a7882297f45e71e9R51-R52))
> Adds the missing changeset to fix the `Type `{}` is missing...` bug

- internal/legacy.faustjs.org/.gitignore
- internal/legacy.faustjs.org/docs/changelog/core.mdx
- internal/legacy.faustjs.org/docs/changelog/faustwp.mdx
- internal/legacy.faustjs.org/docs/changelog/next.mdx
- internal/legacy.faustjs.org/docs/changelog/react.mdx
- internal/legacy.faustjs.org/package-lock.json
- internal/legacy.faustjs.org/package.json
- internal/legacy.faustjs.org/scripts/downloadChangelogs.js
This PR introduces a script in the docs site that first downloads the changelogs from the Git repo and places them in a `.changelogs` directory for consuption for our Docusaurus app. This approach has changed from pulling the changelogs from the relative directory above because we are now using an Atlas site with the root directory specified as `internal/website`. This means that our Atlas instance will no longer have access to the whole monorepo, instead just the website files.
> Download Changelogs

- .changeset/nine-rats-love.md
- packages/faustwp-cli/.npmignore
- packages/faustwp-core/.npmignore
Exclude unnecessary files in production NPM release.
> Add `.npmignore` files to `@faustwp` packages

- .changeset/wicked-buttons-relax.md
- .changeset/wicked-lamps-hang.md
- internal/faustjs.org/docs/faustwp/settings.mdx
- internal/faustjs.org/docs/next/getting-started.mdx
- internal/faustjs.org/docs/tutorial/setup-faustjs.mdx
- internal/legacy.faustjs.org/docs/next/guides/post-page-previews.mdx
- package-lock.json
- plugins/faustwp/faustwp.php
- plugins/faustwp/includes/detect-conflicts/callbacks.php
- plugins/faustwp/includes/detect-conflicts/functions.php
- plugins/faustwp/includes/settings/callbacks.php
- plugins/faustwp/includes/settings/functions.php
- plugins/faustwp/includes/settings/views/headless-settings.php
- plugins/faustwp/includes/utilities/functions.php
- plugins/faustwp/package.json
- plugins/faustwp/readme.txt
- plugins/faustwp/tests/_support/AcceptanceTester.php
- plugins/faustwp/tests/acceptance/SettingsCest.php
- scripts/versionPlugin.js
Changes include:
- Removal of "WP" from "FaustWP" and all other references within the human readable text of the plugin
- Adds new contributors 🎉 
- Update settings menu from "Headless" to "Faust"
- Small documentation typo in `/internal/legacy.faust.org`
References to "Settings -> Headless" have been updated within `/internal/faust.org`
> Remove WP from human readable text in plugin

- internal/faustjs.org/sidebars.js
- internal/legacy.faustjs.org/sidebars.js
Moves the migration guide sidebar menu item from `internal/legacy.faustjs.org/sidebar.js` to `internal/faustjs.org/sidebars.js`
> Moves migration guide sidebar item from legacy to new faust docs site

- .changeset/large-bobcats-relax.md
- packages/faustwp-cli/README.md
- packages/faustwp-core/README.md
This PR updates the `@faustwp` package readmes and modifies a changeset to reflect a `patch` bump instead of a `minor` bump.
`@faustwp/core`: https://github.com/wpengine/faustjs/blob/update-new-faust-readmes/packages/faustwp-core/README.md
`@faustwp/cli`: https://github.com/wpengine/faustjs/blob/update-new-faust-readmes/packages/faustwp-cli/README.md
> Update new faust readmes

- plugins/faustwp/readme.txt
This change updates the [faustwp plugin](https://wordpress.org/plugins/faustwp) to indicate its support for WordPress version 6.1.
> Indicate support for WordPress 6.1

- internal/faustjs.org/package-lock.json
- internal/faustjs.org/package.json
- internal/legacy.faustjs.org/package-lock.json
- internal/legacy.faustjs.org/package.json
This PR removes the `docusaurus` dependency from the `internal/legacy.faustjs.org`/`internal/faustjs.org` packages as we use `@docusaurus/core` now.
The `package-lock.json` changes reflect the removal of the `docusaurus` package.
> Removes the `docusaurus` package since we use `@docusaurus/core` instead

- .changeset/dry-kings-heal.md
- packages/faustwp-core/src/config/withFaust.ts
- packages/faustwp-core/tests/auth/authorize.test.ts
Fixing this improper Lodash import saves about ~20k of JS to the bundle.
`@faustwp/core` before fix: 164k
`@faustwp/core` after fix: 141k
> Use proper Lodash import statement to reduce bundle size

- .changeset/serious-lizards-count.md
- packages/faustwp-core/src/lib/getWpUrl.ts
Trims leading/ending backslashes from `NEXT_PUBLIC_WORDPRESS_URL` to avoid breaking the GraphQL connection.
> Trim backslashes from `NEXT_PUBLIC_WORDPRESS_URL`

- .changeset/twenty-flies-tap.md
- packages/faustwp-cli/index.ts
- packages/faustwp-cli/utils/marshallTelemetryData.ts
- packages/faustwp-cli/utils/sendTelemetryData.ts
This PR finalizes the telemetry implementation by removing the debug endpoint with the production endpoint and also collects the command that was run.
Events are being displayed in Google Analytics:
> Finalize telemetry

- .changeset/chatty-planes-search.md
- packages/faustwp-cli/index.ts
This PR fixes a bug when setting the improper `NODE_ENV` when `faust start` is ran. This PR also fixes a bug that halts CI/Node environments (when the env has no telemetry preferences set) like Atlas when running `faust start`
> CLI: Check for `faust start` command

- internal/faustjs.org/docusaurus.config.js
- internal/legacy.faustjs.org/docusaurus.config.js
This PR makes Docusaurus look for the `SITE_NO_INDEX` env var to determine if the site should be indexed or not on search engines. We can use this when deploying dev/unreleased docs sites. Defaults to `false` when the env var is not configured
> Docs Site: Add "no index" feature

- internal/faustjs.org/docs/authentication.mdx
- internal/faustjs.org/docs/faq.mdx
- internal/faustjs.org/docs/faustwp/seed-query.mdx
- internal/faustjs.org/docs/faustwp/settings.mdx
- internal/faustjs.org/docs/getting-started.mdx
- internal/faustjs.org/docs/next/guides/post-page-previews.mdx
- internal/faustjs.org/docs/next/guides/project-walkthrough.mdx
- internal/faustjs.org/docs/next/reference/getNextServerSideProps.mdx
- internal/faustjs.org/docs/next/reference/getNextStaticProps.mdx
- internal/faustjs.org/docs/sitemaps.mdx
- internal/faustjs.org/sidebars.js
After meeting with devrel to conduct a site audit, the following feedback was provided on readability: 
- Placeholders for Auth and Sitemaps docs added (similar to migration doc placeholder)
- Copy over FAQs page from plugin and add to docs sidebar
- Create uniform headers for all docs (title casing)
- Change bold use for feature highlighting in doc text to code snippets instead to match Atlas docs
This PR addresses the above feedback items.
Use the Atlas preview link below to review the site. Alternatively, you can review locally by:
`cd` into the `internal/faustjs.org/` file
`npm run build`
`npm run dev`
Please check to ensure documents are corrected and sidebar is up to date.
> Merl 616 implement devrel feedback on new faust site

- internal/faustjs.org/docusaurus.config.js
Add a link to the legacy docs in the header for those coming to faustjs.org looking for the legacy docs.
> Add Legacy Docs link in header

- internal/faustjs.org/docs/next/guides/post-page-previews.mdx
The page previews [here](https://faustjs.org/docs/next/guides/post-page-previews) have a glitch in two code snippets in light mode, where they have a dark bar over the code.
Code snippets had what appears to be an unnecessary line count at the top of the two code snippets in the page previews. After deleting the count the glitch is gone from each snippet.
Screenshots of fixed snippets:
> Removed dark lines in code snippets

- .changeset/large-eagles-serve.md
- packages/faustwp-core/src/index.ts
Adds the following functions to the `@faustwp/core` export:
* `getWpUrl`
* `getGraphqlEndpoint`
* `getApolloClient`
* `addApolloState`
> Add `client`/`lib` functions to `@faustwp/core` export

- README.md
Update Readme shields
View shields here: https://github.com/wpengine/faustjs/tree/update-readme-shields
> Update readme shields

- .changeset/ten-steaks-roll.md
- packages/faustwp-cli/index.ts
- packages/faustwp-cli/package.json
- packages/faustwp-cli/utils/disableCliInteraction.ts
- packages/faustwp-cli/utils/index.ts
- packages/faustwp-cli/utils/validateFaustEnvVars.ts
- packages/faustwp-core/DEVELOPMENT.md
- packages/faustwp-core/package.json
- packages/next/test/useCheckFaustContext.test.tsx
- packages/next/test/withFaust.test.ts
These changes add a new env variable, `FAUST_NO_INTERACTION`, intended for CI/CD environments.
1. Checkout `MERL-642-telemetry-env-var`
2. Add `FAUST_NO_INTERACTION=1` to the faustwp example project .env. 
3. Delete any existing faust config: `rm -rf ~/.config/configstore/faust.json`
4. Build CLI: `npm run build:faust-cli`
5. Start Example Project: `npm run dev --workspace=@faustwp/getting-started-example`
6. Notice that project prompts (currently just telemetry) is disabled.
> Add `FAUST_NO_INTERACTION` option to .env

- internal/faustjs.org/docs/migrationPath/portfolio-migration.mdx
- internal/faustjs.org/sidebars.js
This document includes:
- An overview of the changes needed in the [blueprint-portfiolio](https://github.com/wpengine/atlas-blueprint-portfolio) repo
- The file changes and rationale
- The files and areas in each file where the user should make changes (linked to main migration doc)
- Any supporting documentation or links added as needed to help clarify concepts
Atlas previews should show the site's changes and provide you with an opportunity to click through to ensure it is working. Locally, you can:
From the root, cd into the `faustjs.org` folder.
In the command line, run `npm run build`
run `npm run dev'
> Merl 489 migration path for portfolio blueprint documentation

- .changeset/dirty-beds-cover.md
- packages/faustwp-cli/index.ts
Fixes issue when Faust CLI does not return non zero exit code on unsuccessful build.
https://wpengine.atlassian.net/browse/MERL-656
* Try to build a site that has build errors and echo the exit code. It should be `!= 0` when there is a build error:
**Before:**
```
> @faustwp/getting-started-example@0.1.0 build
> faust build
> Build error occurred
Error: Export encountered errors on following paths:
/: /en
/example: /en/example
at /Users/theo.despoudis/Workspace/faustjs/node_modules/next/dist/export/index.js:394:19
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Span.traceAsyncFn (/Users/theo.despoudis/Workspace/faustjs/node_modules/next/dist/trace/trace.js:79:20)
at async /Users/theo.despoudis/Workspace/faustjs/node_modules/next/dist/build/index.js:11 …
```
> Fix: Captures CLI process exit code

- internal/faustjs.org/docusaurus.config.js
- internal/faustjs.org/package-lock.json
- internal/faustjs.org/package.json
- package-lock.json
Fix redirect from docs/next to docs/
To test this, run npm run build and npm run dev locally. Once the site is live, navigate to <site>/docs/next/getting-started. It should redirect you to <site>/docs/getting-started
> MERL-654: updated to get rid of the 404 error with docs/next

- internal/faustjs.org/docusaurus.config.js
- internal/faustjs.org/package-lock.json
- internal/faustjs.org/package.json
This PR adds[ GA's tracking utility ](https://developers.google.com/tag-platform/gtagjs/install)to the faustjs.org website. It uses[ docusaurus' plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag#anonymizeIP) to do so, with the `gtag` sourced from a new GA account for faustjs.org. 
Test changes locally by checking for the `gtag` in the production site's html in the browser (remember to cd into faustjs.org, and then build and run the production branch [`npm run build`, and then `npm run start`]). It should be located in the `<head>` section of every site page's html and looks like this:
**Note:** full testing of the GA data collection cannot happen until a push to production has occurred on the live site, since docusaurus' GA plugin only works in production.
> Merl 655 add analytics to faustjs org

- .changeset/light-donkeys-admire.md
This changeset was generated for https://github.com/wpengine/faustjs/pull/1120 in order to include these changes with the next release of our [WordPress plugin](https://wordpress.org/plugins/faustwp/).
Props to @TeresaGobble for calling this out!
> Generate changeset for latest plugin updates

- .changeset/fresh-pandas-pull.md
- .changeset/grumpy-windows-provide.md
- .changeset/modern-bulldogs-clap.md
- .changeset/new-birds-brush.md
- packages/faustwp-core/src/client.ts
- packages/faustwp-core/src/getWordPressProps.tsx
This PR introduces `props` and `revalidate` to the `getWordPressProps` options config object. It also sets a default `revalidate` to `900` (15 minutes) when using `getStaticProps`.
Also cleaned up the PRs to have each change have it's own changeset so it's reflected properly in the changelog.md
1. Pull in the PR
2. Update `[...wordpressNode].js` with the following content:
```js
import { getWordPressProps, WordPressTemplate } from '@faustwp/core';
export default function Page(props) {
return <WordPressTemplate {...props} />;
}
export async function getStaticProps(ctx) {
const appProps = await getWordPressProps({
ctx,
props: {
myProp: 'testing',
},
});
console.log(appProps);
return appProps;
}
export async function getStaticPaths() {
return {
paths: [],
fallback: 'blocking',
};
}
```
3. …
> Support props/revalidate in getWordPressProps

- .changeset/config.json
- .github/actions/release-plugin/deploy.sh
- .github/workflows/release-plugin.yml
This PR automates the release of the WordPress plugin by instructing Changesets to create tags for private packages.
https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md
This will result in a tag being created for the WordPress plugin (`@faustwp/wordpress-plugin@x.x.x`) when we merge in the "Version Packages" PR with plugin changes.
> Automate WP Plugin Tag and Release

- internal/faustjs.org/blog/2023-01-04-faust-update-jan-04-2023.md
> Add sprint blog post

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
These changes provide more details regarding the current CLA process.
> Update CLA docs

- .changeset/tasty-ads-grin.md
- internal/faustjs.org/docs/plugin-system/creating-a-plugin.mdx
- internal/faustjs.org/docs/plugin-system/filters.mdx
- internal/faustjs.org/sidebars.js
- internal/faustjs.org/src/components/Features/HomepageFeatures.js
- packages/faustwp-core/src/config/index.ts
- packages/faustwp-core/src/hooks/index.ts
- packages/faustwp-core/src/hooks/overloads.ts
- packages/faustwp-core/src/index.ts
- packages/faustwp-core/tests/config/index.test.ts
Created two new TypeScript types for type checking Faust Plugins: `FaustPlugin` and `FaustHooks`, which work like:
```tsx
import { FaustHooks, FaustPlugin } from '@faustwp/core';
export class MyPlugin implements FaustPlugin {
apply(hooks: FaustHooks) {}
}
```
This allows for intellisense to pick up the different types of filters that are available and their signatures:
Added docs that describe the filters and their context objects and signatures. Additionally added a short doc describing how to create a Faust plugin.
> Plugin System TypeScript helpers and Docs

- .github/workflows/sonarqube-scan.yml
These changes remove Sonarqube scans for pull requests into `canary` in order to prevent failed builds for outside contributors.
Sonarqube scans will continue to run against all new code for pull requests into `main`.
> Limit Sonarqube scans to main branch pull requests

- .changeset/flat-rivers-enjoy.md
- package-lock.json
- package.json
- packages/blocks/.eslintignore
- packages/blocks/.npmignore
- packages/blocks/CHANGELOG.md
- packages/blocks/LICENSE
- packages/blocks/README.md
- packages/blocks/jest.config.js
- packages/blocks/jest.setup.ts
- packages/blocks/package.json
- packages/blocks/src/components/DefaultBlock.tsx
- packages/blocks/src/components/WordPressBlocksProvider.tsx
- packages/blocks/src/components/WordPressBlocksViewer.tsx
- packages/blocks/src/index.ts
- packages/blocks/src/resolveBlockTemplate.ts
- packages/blocks/tsconfig.cjs.json
- packages/blocks/tsconfig.json
Adds a new package named `@faustwp/blocks` with its main implementation.
You may want to see this [example repo](https://github.com/wpengine/faustjs/tree/MERL-538/examples/next/faustwp-getting-started) on how to use it.
1. Make sure you install the wp-content-blocks-plugin on your site. Specifically use the [MERL-542](https://github.com/wpengine/wp-graphql-content-blocks/tree/MERL-542) Branch as it contains a few bug fixes.
1. Use the [WordPressBlocksProvider](https://github.com/wpengine/faustjs/blob/MERL-538/examples/next/faustwp-getting-started/pages/_app.js#L14-L19) passing on the list of block components.
2. On your WordPressTemplate, import the [WordPressBlocksViewer](https://github.com/wpengine/faustjs/blob/MERL-538/examples/next/faustwp-getting-started/wp-templates/single.js#L3) …
> Feat: Initial Bootstrap of @faustwp/blocks package

- internal/faustjs.org/docs/getting-started.mdx
- internal/faustjs.org/src/components/GetStarted/HomepageGetStarted.js
- internal/legacy.faustjs.org/docs/next/getting-started.mdx
- internal/legacy.faustjs.org/docs/next/guides/authentication.mdx
- internal/legacy.faustjs.org/src/components/GetStarted/HomepageGetStarted.js
There are two videos across three pages:
[Authentication](https://legacy.faustjs.org/docs/next/guides/auth) (informational; not in faustjs, but in legacy site)
[Getting Started with Faust](https://faustjs.org/docs/next/getting-started) (decorative; in both faustjs and legacy site)
[Main Page](https://faustjs.org/) (decorative; in both faustjs and legacy site)
This PR adds an `aria-hidden="true"` to the Getting Started and Main Page videos (they are the same decorative video). The `aria-hidden="true"` is added here as the videos are decorative in nature, so that the screen reader will skip over them without pause.
An additional paragraph has been added to the authentication video, using `aria-describedby`, which will skip the video and provide a text description below it.
All sections are …
> Merl 253 provide text description for videos on docs website

- .changeset/itchy-ways-applaud.md
- packages/faustwp-cli/utils/shouldFireTelemetryEvent.ts
This PR removes the command constraint (that the command either needs to be `dev` or `build`) to sent a telemetry request.
The idea of only allowing telemetry events on `faust dev` or `faust build` was to ensure that the interactive prompt did not interfer with user's CI/CD pipelines. Now that we have done away with the interactive prompt and instead have a simple console message describing how users can enable/disable telemetry, this is no longer a concern.
Additionally, we have made it clear in our docs that we collect the command, so no changes are needed to what we collect docs:
https://faustjs.org/docs/telemetry#node-environment
A user running `npm start` with no telemetry preferences saved. As you can see the telemetry message is called, but obviously is non blocking. You could …
> Remove the command constraint from the telemetry event being sent

- .changeset/olive-nails-argue.md
- packages/faustwp-cli/index.ts
- packages/faustwp-cli/utils/marshallTelemetryData.ts
This PR fixes occurances where we are sending incomplete telemetry data to Google Analytics.
If the request to get telemetry data from WordPress fails, we throw an error and do not make a request to Google Analytics.
1. Check out the branch
2. Uncomment the `console.log` on line 95 of `faustwp-cli/index.ts`
3. Uncomment the telemetry log on line 88 of `faustwp-cli/index.ts`
4. Change your `FAUST_SECRET_KEY` to something invalid
5. Ensure you have opted in for Faust telemetry
6. Run `npm run dev` in the example, and notice the Error "There was a problem retrieving telemetry data from the WordPress instance"
7. Add the proper `FAUST_SECRET_KEY`
8. Re-run `npm run dev` and notice the proper telemetry event with all properties filled out
> Fix telemetry data

- .changeset/bright-elephants-fly.md
- package-lock.json
- packages/faustwp-cli/.eslintrc
- packages/faustwp-cli/index.ts
- packages/faustwp-cli/package.json
These changes fix an issue where the child process for Next.js CLI was preventing the node server from starting up in a Windows environment.
- #1144 
Currently no CI/CD tests, so a VM or Windows machine is required to test these changes.
1. Checkout this branch in a Windows environment.
2. Run `npm run build -w @faustwp/cli` to build these changes.
3. Run `npm run dev -w @faustwp/getting-started-example` to run example project.
4. Notice that node server serves up example project as expected.
> Fix CLI child process within Windows environment

- .changeset/perfect-gorillas-march.md
- packages/faustwp-core/src/getProps.ts
- packages/faustwp-core/tests/getProps.test.ts
- This PR fixes a bug with `getNextStaticProps` not properly propagating the `revalidate` property causing issues with ISR.
- Adds test cases.
1. Create a Next.js file based page and set revalidate to a low value in getNextStaticProps
2. Update something in WordPress. 
3. The Page is not invalidated after the revalidate time elapsed causing ISR issues.
> [Merl 738] Bug Fix: Propagate `revalidate` in getNextStaticProps`

- .github/actions/run-coverage/action.yml
- .github/workflows/test-packages.yml
- packages/faustwp-cli/.gitignore
- packages/faustwp-cli/package.json
Downgrades our Jest coverage action from 2.2 to 2.1.2 as it looks like the most recent release is broken/had breaking changes.
Additionally, the FaustWP CLI and FaustWP Core coverage reports are now visible and I've removed the legacy packages.
> Code coverage for new faust

- examples/next/faustwp-getting-started/components/NavigationMenu/NavigationMenu.js
Remove an extra argument when renderMenu is called recursively in the example NavigationMenu component. 
#1235 
Removed the extra argument in my own repo and no errors were observed.
> fix: (1235) remove unneeded argument in function call

- .changeset/dry-melons-talk.md
- internal/faustjs.org/docs/templates.mdx
- packages/faustwp-core/src/getWordPressProps.tsx
This adds locale to the context for templates. more information can be found on the linked issue.
- #1228
I did not create any tests for this change, I tried to look for tests that would cover this code but I didn't see any and thus, I didn't create any since its such a small change.
No visual change
With adding locale to the context, I have updated the document located at https://faustjs.org/docs/templates to correct the interface for the Component.variables.
None
I did not create a changeset as I didn't know if it was required for my change. Please let me know if its required (I couldnt tell from [this](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#code-changesfeature-workflow) doc).
> feat[faustwp-core]: (1228) add locale to the context sent down to the component variables in template

- examples/next/faustwp-getting-started/faust.config.js
- packages/faustwp-core/src/components/FaustProvider.tsx
- packages/faustwp-core/src/config/index.ts
Updated config to include experimental flag for the toolbar.
1. Check that the default for enableExperimentalToolbar=false and that the toolbar doesn't show.
2. Update the faust.config.js to set enableExperimentalToolbar=true and make sure the toolbar displays.
> MERL-753: enableExperimentalToolbar added for toolbar usage

- internal/faustjs.org/docs/next/guides/project-walkthrough.mdx
While reading documentation, I found a few small typos in the project walkthrough documentation. Fixed to increase readability.
> Fixed typos in project walkthrough

- .changeset/clean-planes-impress.md
- packages/faustwp-core/src/config/index.ts
The `disableLogging` property was a reminant of old Faust. This PR removes it from the config type as it was causing issues a type mismatch when using a ts extension for the `faust.config` file.
[Additional context on discord](https://discord.com/channels/836253505944813629/1076600966473842758/1076600966473842758)
> Remove `disableLogging` property from `FaustConfig` type

- internal/faustjs.org/docs/gutenberg/wp-graphql-content-blocks.mdx
Duplicate line in the wp-graphql-content-blocks.mdx. Deleted.
> Deleted duplicate text

- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-wordpress-core.mdx
While reading the `create-a-block-from-wordpress-core.mdx` document, I noticed a few small typos which are fixed in this PR.
> Core blocks tutorial proofing changes

- .changeset/hungry-candles-carry.md
- .changeset/slimy-queens-scream.md
- .changeset/small-guests-itch.md
- packages/faustwp-core/src/hooks/useAuth.tsx
`useAuth` was making numerous calls to the token endpoint due to the `useEffect` rerendering. This PR removes the dependencies causing the unneeded rerender.
1. Checkout branch
2. Build the libraries
3. Create `pages/auth.js` in example project with the following content:
```jsx
import { useAuth } from '@faustwp/core';
export default function Auth() {
const { isAuthenticated } = useAuth();
return <>Auth page</>;
}
```
4. Run the dev server and visit `/auth`
5. Check the network tab and only see one request to the token endpoint.
Before:
After:
> useAuth: Only make request to token endpoint once, add changesets

- .changeset/orange-terms-try.md
- examples/next/faustwp-getting-started/.env.local.sample
- packages/faustwp-core/src/components/Toolbar/ToolbarNodeSkeleton.tsx
- packages/faustwp-core/src/components/Toolbar/index.ts
- packages/faustwp-core/src/components/Toolbar/nodes/MyAccount.tsx
- packages/faustwp-core/src/styles/_body-classes.scss
- packages/faustwp-core/src/styles/_loaders.scss
- packages/faustwp-core/src/styles/toolbar.scss
These changes introduce a new skeleton component that replaces internal "Loading..." fragments. This component has also been made available for users to use in custom nodes.
1. Checkout this branch: `MERL-698-skeleton-loader`
2. Run `npm run build -w @faustwp/core`
4. Drop [this Faust plugin](https://gist.github.com/josephfusco/b781839e8c33dc729b64f94eaa8a57c3) into your test site
5. Register the plugin from step 3 in `faust.config.js`
```js
experimentalPlugins: [new CustomToolbar()],
```
6. Observe 2 toolbar nodes with a pulsing background.
7. Observe 2 toolbar nodes with a static background when a user's system setting is set to [prefer reduced motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
> Provide skeleton component for individual toolbar nodes

- .changeset/sweet-sloths-grin.md
- packages/blocks/src/components/DefaultBlock.tsx
Changes the default element for `DefaultBlock` from `<span>` to `<div>`.
* Use `WordPressBlocksViewer` to render a list of blocks that are not implemented. The final markup should contain divs for fallback blocks instead of spans.
> Style: Use `div` for `DefaultBlock` instead of `span`

- internal/faustjs.org/docs/guides/custom-toolbar.mdx
These changes add instructions for importing the WordPress toolbar stylesheet and fix syntax highlighting within code blocks.
> Syntax Highlighting for Customizing the Toolbar guide

- .changeset/chilly-lemons-whisper.md
- internal/faustjs.org/docs/guides/custom-toolbar.mdx
- packages/faustwp-core/package.json
- packages/faustwp-core/src/index.ts
- packages/faustwp-core/toolbar.d.ts
These changes fix an issue introduced in `@faustwp/core@0.2.5` where modules were not found.
> Export everything under the main entry point

- internal/faustjs.org/docs/gutenberg/getting-started.mdx
- internal/faustjs.org/docs/gutenberg/migration-from-wp-graphql-gutenberg.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-third-party.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-wordpress-core.mdx
- internal/faustjs.org/sidebars.js
- Adds migration guide from wp-graphql-gutenberg.
- Small documentation fixes on other gutenberg pages.
New Docs Page:
`docs/gutenberg/migration-from-wp-graphql-gutenberg`
> MERL-709 - Docs: Migration Guide from wp-graphql-gutenberg

- internal/faustjs.org/docs/guides/custom-toolbar.mdx
These changes highlight the need to authenticate with WordPress in order to see the Toolbar.
See https://hwcvtvdvg76996xabddre5dwq.js.wpenginepowered.com/docs/guides/custom-toolbar#login-to-your-site
> Update customizing the toolbar guide

- internal/faustjs.org/docs/gutenberg/getting-started.mdx
- internal/faustjs.org/docs/gutenberg/migration-from-wp-graphql-gutenberg.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-third-party.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-wordpress-core.mdx
- internal/faustjs.org/docs/gutenberg/wp-graphql-content-blocks.mdx
- internal/faustjs.org/docs/reference/WordPressBlocksViewer.mdx
- packages/blocks/README.md
This PR changes `nodeId` -> `clientId` and `parentId -> parentClientId` references as per recommendation
https://github.com/wpengine/wp-graphql-content-blocks/issues/15
* Updates in the Gutenberg tutorials
> Docs: Update references to `nodeId` and `parentId`

- internal/faustjs.org/docs/next/reference/getNextStaticProps.mdx
Update docs references in `getNextStaticProps.mdx` to refer to static props instead of server-side props.
> Update getNextServerSideProps to getNextStaticProps

- .changeset/beige-owls-glow.md
- internal/faustjs.org/docs/faustwp/filters.mdx
- internal/faustjs.org/docs/faustwp/settings.mdx
- internal/faustjs.org/sidebars.js
- plugins/faustwp/includes/deny-public-access/callbacks.php
These changes are based on the originally proposed solution from https://github.com/wpengine/faustjs/pull/740. Unfortunately that GitHub account is no longer active.
These changes will close https://github.com/wpengine/faustjs/issues/739.
1. Create the pages "checkout" & "cart" in WordPress.
2. Make sure the "Enable public route redirect" setting is active within the Faust WordPress plugin.
3. Make sure that your front-end URL is using `http://localhost:3000`
4. Observe that the WordPress pages `/checkout` and `/cart` redirect to their corresponding pages on `http://localhost:3000`
5. Add the following snippet to your WordPress site (bottom of the active theme's `/functions.php` is fine for this)
```php
add_filter( 'faustwp_exclude_from_public_redirect', function( $excluded ) {
$excluded …
```
> Add `faustwp_exclude_from_public_redirect` filter to companion WordPress plugin

- .changeset/thirty-apricots-compare.md
- packages/faustwp-core/src/getProps.ts
- packages/faustwp-core/src/getWordPressProps.tsx
This PR rectifies the return types of `getWordPressProps` and `getNextStaticProps` for TS.
Fixes: https://github.com/wpengine/faustjs/issues/1340
- Create a new Project using TS
- Try to assign a return type for `getWordPressProps` in `getServerSideProps` and `getStaticProps`
```
export const getServerSideProps: GetServerSideProps = async (
ctx: GetServerSidePropsContext
) => getNextServerSideProps(ctx, {Page, props: {title: 'File Page Example'}});
```
```
export const getServerSideProps: GetServerSideProps = async (
ctx: GetServerSidePropsContext
) => getWordPressProps({ ctx });
```
It should not fail to typecheck when running `npm build`
> TS: Fix getWordPressProps/getNextStaticProps invalid return type

- .changeset/four-days-hang.md
- packages/blocks/package.json
This PR corrects the package.json type reference in the @faustwp/blocks package to use the correct types.
https://github.com/wpengine/faustjs/issues/1337
1. Create a new TS project and try to import `@faustwp/blocks` package.
2. It should not complain for non-existing type definitions for the @faustwp/blocks package
> [@faustwp/blocks] Use correct types for @faustwp/blocks package in package.json

- .changeset/eleven-walls-hear.md
- .changeset/sour-eggs-remain.md
- packages/blocks/src/components/WordPressBlocksProvider.tsx
- packages/blocks/src/components/WordPressBlocksViewer.tsx
- packages/blocks/src/resolveBlockTemplate.ts
- packages/faustwp-core/src/getWordPressProps.tsx
- packages/faustwp-core/src/index.ts
This PR Improve TS types for the `WordPressBlock`, `WordpressBlocksViewer` and exposes a dedicated type for WordPressTemplate called `FaustTemplate`. This is mainly to address the feedback from https://github.com/wpengine/faustjs/issues/1339  and https://github.com/wpengine/faustjs/issues/1338
This should compile without issues:
```ts
import { FaustTemplate } from '@faustwp/core';
import { PageDocument, PageQuery } from './page.generated';
const Page: FaustTemplate<PageQuery> = ({ data }) => (
<div className="page-wrapper">
<h1>{data?.page?.title}</h1>
{!!data?.page?.contentBlocks && (
<WordPressBlocksViewer contentBlocks={data.page.contentBlocks} />
)}
</div>
);
Page.query = PageDocument;
Page.variables = (seedNode, context) => ({
databaseId: seedNode.databaseId,
});
export default Page; …
```
> Bug: Improve TS types for Blocks and Templates

- internal/faustjs.org/docs/gutenberg/getting-started.mdx
- internal/faustjs.org/docs/gutenberg/wp-graphql-content-blocks.mdx
This PR is for one of two to fulfill [MERL-759](https://wpengine.atlassian.net/jira/software/c/projects/MERL/boards/1007?modal=detail&selectedIssue=MERL-759). This changes the documentation to match the new `flat` by default configuration for `editorBlocks`, and explains how to set it to false if desired.
The other pull request that contains the changes to the editorBlocks `flat` arg for MERL-759 is located in the plugin, here: https://github.com/wpengine/wp-graphql-content-blocks/pull/39 
[MERL-759]: https://wpengine.atlassian.net/browse/MERL-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merl 759 wp graphql content blocks set content blocks flat true by default

- .changeset/eleven-walls-hear.md
- packages/blocks/src/components/WordPressBlocksViewer.tsx
Returning a `div` from the `WordPressBlockViewer` was messing with styles and CSS selectors. Replacing it in favor of a React fragment.
> Return fragment from blocks

- plugins/faustwp/readme.txt
These changes update the "tested up to value" for the Faust WordPress plugin after testing the plugin within 6.2-RC5.
**No Changeset found** is intentional as there are no code changes here.
This might have to wait for some code changes to push this update into SVN.
- See https://github.com/wpengine/faustjs/pull/875
> Bump WP tested up to 6.2

- .changeset/clean-doors-travel.md
- packages/blocks/src/components/WordPressBlocksViewer.tsx
This PR throws a human readable error if the `blocks` prop does not exist on the `WordPressBlocksViewer` component.
> Throw an error if "blocks" prop does not exist on WordPressBlocksViewer

- .changeset/lucky-islands-deny.md
- .changeset/sweet-seas-appear.md
- packages/faustwp-core/src/getProps.ts
- packages/faustwp-core/src/index.ts
- packages/faustwp-core/tests/getProps.test.ts
This PR adds the Next.js file based page's query response as `props.data` in both `getNextServerSideProps` and `getNextStaticProps`
Additionally, adds a `FaustPage` type much like `FaustTemplate` to help properly type Next.js pages that use Faust helpers.
1. Checkout this PR
2. Build core `npm run build -w @faustwp/core`
3. Run the example project `npm run dev -w @faustwp/getting-started-example`
4. In the `example.js` page, console.log the `props`
5. Notice that there is now `props.data` which includes the `Page.query`'s data, and `__PAGE_VARIABLES__` prop, which includes the computed variables (this value should not really be used, but we include it just in case to be compatible with the Faust Templates)
> Pass data and variables in next helpers

- packages/faustwp-core/package.json
- packages/faustwp-core/src/components/Toolbar/Toolbar.tsx
- packages/faustwp-core/tests/components/Toolbar/Toolbar.test.tsx
- plugins/faustwp/includes/graphql/callbacks.php
This PR shows or hides the Faust Toolbar based on the user's toolbar preferences in WordPress:
A field was added to the `viewer` model in WPGraphQL called `shouldShowFaustToolbar` which we use to either show or hide the toolbar component.
If the user is using a version of Faust where this field does not exist, the query will throw an error, and show the toolbar. If the query fails, there is no blocking errors, the behavior just falls back to showing the toolbar.
Tests have been provided. Additionally, here are some manual testing instructions:
1. Checkout this branch
2. Build the core and cli packages
3. In the example app, ensure `experimentalToolbar` is set
4. Make sure you are using the version of FaustWP from this branch
5. Start the dev server
6. Authenticate via previews
7. Notice …
> Show Faust Toolbar based on user preferences in WordPress

- .changeset/popular-melons-fold.md
- packages/faustwp-core/src/index.ts
Expose the `hooks` from the plugin system so other packages can register their own filters and actions.
For example:
```js
import {hooks} from '@faustwp/core'
function MyPackageLogic() {
let items = [];
items = hooks.addFilter('myFilter', items)
return items;
}
```
> Expose hooks in Faust Core

- internal/faustjs.org/docs/gutenberg/getting-started.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-third-party.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-block-from-wordpress-core.mdx
- internal/faustjs.org/docs/gutenberg/tutorial/create-a-custom-block.mdx
This PR adds several note sections in the docs, clarifying the use of declaring `displayName` and `config.name` properties in Block Components.
This is to ensure any production build does resolve to the correct blocks instead of rendering the DefaultBlock.
Changes in all Gutenberg doc pages when declaring block component code.
> Docs: Clarify usage of `displayName` on production builds

- .changeset/swift-impalas-kneel.md
- internal/faustjs.org/docs/plugin-system/filters.mdx
- packages/faustwp-core/src/getWordPressProps.tsx
- packages/faustwp-core/src/wpHooks/overloads.ts
This filter allows you to modify the resolved URL in the Faust template system, say for instance, adding or striping a locale from a URL.
> Add `resolvedUrl` filter for modifying the resolved URL in the Faust template system

- internal/faustjs.org/docs/gutenberg/how-to-query-blocks.mdx
Adds sections in the `how-to-query-blocks` page about using the new `BlockWithSupportsAnchor` interface.
* Updated `docs/gutenberg/how-to-query-blocks`
> Docs: Add example with `BlockWithSupportsAnchor`

- .changeset/bright-bugs-cry.md
- .changeset/loud-cars-knock.md
- audit-ci.jsonc
- internal/faustjs.org/docs/global-stylesheet.mdx
- internal/faustjs.org/sidebars.js
- packages/faustwp-cli/src/generateGlobalStylesheet.ts
- packages/faustwp-cli/src/index.ts
- plugins/faustwp/faustwp.php
- plugins/faustwp/includes/graphql/callbacks.php
- plugins/faustwp/readme.txt
These changes registered a new GraphQL field, `globalStylesheet`, that returns [wp_get_global_stylesheet](https://developer.wordpress.org/reference/functions/wp_get_global_stylesheet/) and exposes the same arguments as the core WordPress function.
If no arguments are used, it'll load the following:
for themes without theme.json: `VARIABLES`, `PRESETS`, `BASE_LAYOUT_STYLES`.
for themes with theme.json: `VARIABLES`, `PRESETS`, `STYLES`.
These changes also include some legal adjustments to appropriately reference the Faust.js™ trademark.
There is really no need for unit tests here as these changes are simply exposing WordPress core functionality.
1. Checkout this branch: `MERL-766-expose-global-css`
2. Query the global stylesheet without arguments
```
query GlobalStylesheet { …
```
> Add support for querying the WordPress global stylesheet

- .github/workflows/deploy-plugin.yml
- .github/workflows/release-packages.yml
This PR fixes automatic plugin deployments from changesets, and also creates a workflow that can be invoked manually via the "actions" tab in GitHub.
Testing was done in my private GitHub repo for changesets testing and I can confirm that the conditional statement worked as expected.
> Fix Plugin Deploy / Add workflow to manually deploy plugin if needed

- .changeset/cool-owls-battle.md
- packages/faustwp-core/src/getTemplate.ts
- packages/faustwp-core/tests/getTemplate.test.ts
Adds support for WordPress [Page Templates](https://developer.wordpress.org/themes/template-files-section/page-template-files/) in the Faust template system.
Unit tests have been added.
To manually test, do the following:
1. Checkout this PR
2. Build the packages
3. Run the dev server
4. Navigate to a single page/post
5. Notice at the top of the possible templates you have `template-Default`
6. Now create a custom Page Template in your WP theme called `ContentWithoutSidebar.php`
7. Go to a page and select that template for the page
8. Now, view that page in the Faust app
9. Notice at the top of the possible templates list you have `template-ContentWithoutSidebar`
> Support WordPress template in possible templates list

- internal/faustjs.org/docs/reference/useBlocksTheme.mdx
- internal/faustjs.org/sidebars.js
- package-lock.json
- package.json
- packages/blocks/.gitignore
- packages/blocks/package.json
- packages/blocks/src/components/WordPressBlocksProvider.tsx
- packages/blocks/src/components/WordPressBlocksViewer.tsx
- packages/blocks/src/index.ts
- packages/blocks/src/theme.ts
- packages/blocks/tests/components/WordPressBlocksProvider.test.tsx
This PR adds the `theme` property to the `WordPressBlocksProvider` config object that can then be retrieved with the `useBlocksTheme()` hook.
Unit tests have been provided.
> Add theme property in `WordPressBlocksProvider`

- .changeset/hungry-fans-end.md
- internal/faustjs.org/docs/faustwp/settings.mdx
- plugins/faustwp/includes/settings/functions.php
- plugins/faustwp/tests/acceptance/SettingsCest.php
The default plugin setting for "Disable WordPress Theme Admin Pages" is now unchecked, requiring a user to opt-in after initial activation.
1. Create a new WordPress site (or deactivate faustwp in an existing site & run `wp option delete faustwp_settings` within the site shell to mock a fresh install)
2. Activate faustwp
3. Observe that the setting "Disable WordPress Theme Admin Pages" is unchecked. See screenshot.
> Admin should have to opt-in to disabling theme pages

- packages/faustwp-core/src/getTemplate.ts
- packages/faustwp-core/tests/getTemplate.test.ts
We should not include `template-Default` in the possible template list. Since templates have the highest priority, if the default template is specified, it will override every single page. Take for instance the home page (`front-page`). If they have a template for the default, it would be used over `front-page`, which you wouldn't expect.
Instead, only add WordPress templates to the possible templates list if they are not default.
> Remove `template-Default` from possible template list

- .github/workflows/e2e-nightly-build.yml
This PR invokes a new action after successfully releasing the nightly builds to then do a production build with the [`faust-scaffold-ts`](https://github.com/wpengine/faust-scaffold-ts) project while updating the dependencies to use the newly released nightly packages.
> Create e2e nightly build action

- .changeset/tall-files-sort.md
- examples/next/faustwp-getting-started/package.json
- packages/blocks/package.json
- packages/blocks/src/blocks/CoreParagraph.tsx
- packages/blocks/src/blocks/index.ts
- packages/blocks/src/components/WordPressBlocksProvider.tsx
- packages/blocks/src/index.ts
- packages/blocks/tests/blocks/CoreParagraph.test.tsx
* Provides reference implementation of CoreParagraph block. 
* Uses `getStyles` helper/
* Adds Unit tests.
* Follow instructions to configure the `blocks` package in the example project. https://faustjs.org/docs/gutenberg/getting-started
* Generate the global stylessheet and import it into the project. `faust generateGlobalStylesheet`.
```_app.js
import { WordPressBlocksProvider, fromThemeJson } from '@faustwp/blocks';
import themeJson from '../theme.json';
import '../globalStylesheet.css';
export default function MyApp({ Component, pageProps }) {
const router = useRouter();
return (
<FaustProvider pageProps={pageProps}>
<WordPressBlocksProvider
config={{
blocks,
theme: fromThemeJson(themeJson),
}}>
<Component {...pageProps} key={router.asPath} />
</WordPressBlocksProvider> …
```
> Feat: CoreParagraph Block

- .changeset/tall-cougars-sit.md
- examples/next/faustwp-getting-started/components/Container/Container.js
- examples/next/faustwp-getting-started/components/ContentWrapper/ContentWrapper.js
- examples/next/faustwp-getting-started/styles/_blocks.scss
- packages/blocks/src/blocks/CoreColumn.tsx
- packages/blocks/src/blocks/CoreColumns.tsx
- packages/blocks/src/blocks/CoreParagraph.tsx
- packages/blocks/src/blocks/index.ts
- packages/blocks/src/components/WordPressBlocksViewer.tsx
- packages/blocks/src/utils/get-styles/getLayoutStyles.ts
- packages/blocks/src/utils/get-styles/getStyles.ts
- packages/blocks/tests/blocks/CoreColumns.test.tsx
- packages/blocks/tests/utils/get-styles/getLayoutStyles.test.ts
* Provides reference implementation of CoreColums and CoreColumn block. 
* Uses `getStyles` helper/
* Added `getLayoutStyles` to handle layout block styles.
* Adds Unit tests.
* Follow instructions to configure the `blocks` package in the example project. https://faustjs.org/docs/gutenberg/getting-started
* Generate the global stylessheet and import it into the project. `faust generateGlobalStylesheet`.
```_app.js
import { WordPressBlocksProvider, fromThemeJson } from '@faustwp/blocks';
import '../globalStylesheet.css';
export default function MyApp({ Component, pageProps }) {
const router = useRouter();
return (
<FaustProvider pageProps={pageProps}>
<WordPressBlocksProvider
config={{
blocks,
theme: {},
}}>
<Component {...pageProps} key={router.asPath} />
</WordPressBlocksProvider> …
```
> [Merl-904] Feat CoreColumns, CoreColumn, getLayoutStyles

- .changeset/brown-fans-attack.md
- packages/blocks/src/blocks/CoreSeparator.tsx
- packages/blocks/src/blocks/index.ts
- packages/blocks/tests/blocks/CoreSeparator.test.tsx
- packages/blocks/tests/blocks/__snapshots__/CoreCode.test.tsx.snap
* Provides reference implementation of CoreSeparator block. 
* Uses `getStyles` helper/
* Added `getLayoutStyles` to handle layout block styles.
* Adds Unit tests.
* Follow instructions to configure the `blocks` package in the example project. https://faustjs.org/docs/gutenberg/getting-started
* Generate the global stylesheet and import it into the project. `faust generateGlobalStylesheet`.
```_app.js
import { WordPressBlocksProvider, fromThemeJson } from '@faustwp/blocks';
import '../globalStylesheet.css';
export default function MyApp({ Component, pageProps }) {
const router = useRouter();
return (
<FaustProvider pageProps={pageProps}>
<WordPressBlocksProvider
config={{
blocks,
theme: {},
}}>
<Component {...pageProps} key={router.asPath} />
</WordPressBlocksProvider>
</FaustProvider>
); …
```
> [MERL-907]Feat: Add CoreSeparator block

- .changeset/tidy-pandas-live.md
- .changeset/tough-mice-pretend.md
- internal/faustjs.org/docs/telemetry.mdx
- packages/faustwp-cli/src/telemetry/marshallTelemetryData.ts
- packages/faustwp-cli/src/telemetry/requestWPTelemetryData.ts
- plugins/faustwp/includes/rest/callbacks.php
- plugins/faustwp/includes/telemetry/functions.php
These changes add 2 new fields to GA
- `wpgraphql_content_blocks_version`
- `node_faustwp_blocks_version`
- See the latest [Atlas Preview Environment](https://h9p8ppf6bszrcx4mrayge0wfy.js.wpenginepowered.com/docs/telemetry)
> Add `@faustwp/blocks` package version & `wp-graphql-content-blocks` plugin version to Faust.js telemetry

- .changeset/angry-papayas-applaud.md
- packages/faustwp-core/src/auth/client/accessToken.ts
- packages/faustwp-core/tests/auth/client/accessToken.test.ts
- Fixes: https://github.com/wpengine/faustjs/issues/1471
- Adds relevant test cases.
1. Deploy this repo to vercel: https://github.com/theodesp/faust-middleware-basepath-breaks-next-link
2. Make sure you setup Front-end site URL to point to your WP Instance.
3. Navigate to the `/login` path and try to authenticate with WP.
4. Authentication should succeed all the times and you should not see any 500 errors.
**Note** The repo contains a patch-package that contains the fix in order to test on Vercel
https://github.com/theodesp/faust-middleware-basepath-breaks-next-link/blob/main/patches/%40faustwp%2Bcore%2B1.0.1.patch
> [Merl 1023] Bug Fix: `useLogin` access token `code` is now properly escaped.

- .github/workflows/nextjs-bundle-analysis.yml
This change prevents the Next.js Bundle Analysis job from running when syncing canary with main.
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches
- https://github.com/wpengine/faustjs/actions/runs/5523789313/jobs/10075190857
> Exclude `main` from running the Next.js Bundle Analysis workflow

- .changeset/popular-poets-lick.md
- plugins/faustwp/includes/replacement/callbacks.php
- plugins/faustwp/includes/replacement/previewlinks.js
Fixes issue when clicking multiple times the preview button crushes the browser.
https://github.com/wpengine/faustjs/issues/1491
1. Make or edit a new page
2.. Click on the "Preview in new tab" button
3. Once the new tab opens get back to the editor and click the button again
4 Repeat step 2 approximately 10 - 15 times
5 Browser should not become unresponsive.
> Bug: Fix preview link button crushes browser.

- .changeset/polite-dolphins-cover.md
- plugins/faustwp/includes/replacement/functions.php
- plugins/faustwp/includes/replacement/graphql-callbacks.php
- plugins/faustwp/tests/integration/ReplacementFunctionsTests.php
When using ‘url’ as an alias for a featured image’s sourceUrl, Faust is mistaking that image url as one that it should replace. These changes check if those replacement key values contain file extensions, and to skip replacement if true.
Use the following query to test that image URL's are no longer being replaced when using the `url` or `href` key.
```graphql
{
generalSettings {
url # never rewritten
}
posts {
nodes {
title
featuredImage {
node {
normal: sourceUrl # control
url: sourceUrl # url is replaced by faustwp
href: sourceUrl # href is replaced by faustwp
}
}
}
}
}
```
Observe that the 3 alias' for the featured image sourceUrl are not replacing the base url with the frontend uri.
> Prevent base URL replacement in GraphQL response when `url` & `href` key values contain file extensions

- .changeset/brown-swans-pretend.md
- packages/faustwp-core/src/getProps.ts
- packages/faustwp-core/src/getWordPressProps.tsx
- packages/faustwp-core/tests/getProps.test.ts
This PR allows passing extra arguments in `Page.variables()`. This is exposed in `getNextStaticProps`, `getServerSideProps` and `getWordPressProps`.
```
export function getStaticProps(ctx) {
return getWordPressProps({ ctx, extra: {hello: 'world'} }); // extra argument will be forwarded to the Template `variables` callback
}
Component.variables = ({ databaseId }, ctx, extra) => {
console.log(extra) // {hello: 'world'}
...
}
```
* Use the `extra`  field and pass custom parameters in the `getNextStaticProps`, `getServerSideProps` and `getWordPressProps` helpers. There should be passed verbatim as an extra argument to the `variables()` callback.
> [Merl 1018] Allow passing extra arguments in `Page.variables`.

- scripts/versionPlugin.js
Existing link is broken. This updates the link to point to the changelog here in GitHub. I linked to `canary` because `main` is not always up to date with what is deployed (though maybe it should be, separate concern).
> chore: fix changelog link

- .github/workflows/release-packages.yml
We can still rely on the manual release-plugin action do deploy the plugin to the WP repo
This PR removes the automatic deploy step to WordPress.org. This step was broken since it was not executed in a workflow with a proper new tag, the script didn't know what the latest version was to deploy.
This PR removes this step until it's resolved/we come up with a different solution. For now, we can still manually invoke a plugin release via the `release-plugin` action.
> Remove the broken faust plugin release step

- plugins/faustwp/docker-compose.yml
This changes updates the docker database within the faustwp to use MySQL 8.
Observe that the updated workflow is still passing.
> Update plugin tests to use MySQL 8

- .github/workflows/nextjs-bundle-analysis.yml
- Next.js Bundle Analysis job runs only on canary branch and uses correct job syntax.
- Remove `branches-ignore` since it cannot used with `branches` in the same declaration.
> CI/CD: Run Bundle Analysis only on canary branch.

- .github/workflows/audit-dependencies.yml
- .github/workflows/e2e-test-plugin.yml
- .github/workflows/nightly-releases.yml
Updates the GitHub Actions workflows to use the newer versions of `checkout` and `setup-node`, to address the warnings as seen on PRs like this: https://github.com/wpengine/faustjs/actions/runs/5786911890.
Also fixes a misspelling.
> MERL-1168 - ci: update checkout and setup-node actions to v3

- .changeset/rich-rice-mix.md
- packages/block-editor-utils/src/components/Edit.tsx
- packages/block-editor-utils/src/components/Preview.tsx
- packages/block-editor-utils/src/registerFaustBlock.ts
- packages/block-editor-utils/tests/components/Edit.test.tsx
- packages/block-editor-utils/tests/components/Preview.test.tsx
* Adds default Edit function when using registerFaustBlock.
* Implements only Preview mode for now.
* Unit tests.
https://github.com/wpengine/faustjs/issues/1522
1. run `npm install`
2. Build the project 
3. cd inside the project folder:
`cd packages/block-editor-utils`
7. Inside the plugin folder run `npm link @faustwp/block-editor-utils ` to add a reference to the package.
8. Rewrite the genenated `index.js` editor script to use the `registerFaustBlock` helper function instead. 
```js
// index.js
import "./style.scss";
// import block.json
import metadata from "./block.json";
// import …
```
> Feat: (registerFaustBlock) Add Edit Function (Preview mode)

- .github/actions/run-coverage/action.yml
This configures Code Coverage to just generate the report and not comment on PRs. We're not currently actioning these reports, and they're generating a lot of noise. We will revisit in the future. These reports should still be available in the actions output.
See readme for config options: https://github.com/ArtiomTr/jest-coverage-report-action
> ci: configure Code Coverage action to not comment

- packages/block-editor-utils/src/registerFaustBlock.ts
This PR removes the unnecessary `P` TypeScript variable in `registerFaustBlock`
> Remove unnecessary `P` TypeScript variable

- package-lock.json
- packages/block-editor-utils/package.json
- packages/block-editor-utils/src/components/Edit.tsx
- packages/block-editor-utils/src/components/EditFormFields.tsx
- packages/block-editor-utils/src/components/InspectorFields.tsx
- packages/block-editor-utils/src/helpers/getControlFields.ts
- packages/block-editor-utils/src/registerFaustBlock.ts
- packages/block-editor-utils/src/types/index.d.ts
- packages/block-editor-utils/tests/components/Edit.test.tsx
- packages/block-editor-utils/tests/components/InspectorFields.test.tsx
* Implements automatic handling of InspectorFields controls as per RFC document.
* Unit tests added
https://github.com/wpengine/faustjs/issues/1522
1. run `npm install`
2. Build the project 
`npm run build -w packages/block-editor-utils`
4. cd inside the project folder:
`cd packages/block-editor-utils`
`npx @wordpress/create-block hello-world-block`
8. Inside the plugin folder run `npm link @faustwp/block-editor-utils ` to add a reference to the package.
9. Rewrite the genenated `index.js` editor script to use the `registerFaustBlock` helper function instead adding the hook for testing the …
> Feat: InspectorFields component

- package-lock.json
- packages/experimental-app-router/src/index.tsx
- packages/experimental-app-router/src/server-actions/logoutAction.ts
- packages/experimental-app-router/tests/server-actions/onLogout.test.ts
Created the onLogout server action for the app router.
To test this follow these steps:
1. Pull this branch
2. Run `npm install`
3. Navigate in the terminal to the `examples/next/app-router` folder
4. Setup the `env.local` and a local site for Faust. Be sure to set the `frontend url` in the Faust WP Plugin settings.
5. Add the following to the `app-router/app/page.js` file inside the `main` element:
```
// import up top
import { onLogout } from '@faustwp/experimental-app-router';
// inside the <main> body element
<form action={onLogout}>
<button type="submit">Logout</button>
</form>
```
6. Run `npm install` and then `npm run build`
7. Run `npm run dev -w @faustwp/app-router-example`
8. Navigate to your `localhost:3000`
9. You should see your homepage with a `logout` button
10. Add a …
> MERL-1204: onLogout server action - app router

- .changeset/soft-cooks-peel.md
- package-lock.json
- plugins/faustwp/includes/replacement/callbacks.php
- plugins/faustwp/includes/replacement/previewlinks.js
These changes include a proposed fix for https://github.com/wpengine/faustjs/issues/1561.
1. Checkout this branch that includes changes to the **faustwp** plugin: `MERL-1205-refactor-custom-preview`
2. Using the updated **faustwp** plugin, create a new post & save as draft (do not publish)
3. Observe that both preview links correctly resolve to display draft content
> Fix Faust.js WordPress Plugin Preview

- .changeset/curly-toes-cross.md
- packages/block-editor-utils/src/controls/Checkbox.tsx
- packages/block-editor-utils/src/controls/index.ts
- packages/block-editor-utils/src/types/index.d.ts
- packages/block-editor-utils/tests/controls/Checkbox.test.tsx
This PR implements the checkbox control feature for the `block-editor-utils` package. Its corresponding jira ticket is [here](https://wpengine.atlassian.net/jira/software/c/projects/MERL/boards/1007?modal=detail&selectedIssue=MERL-1153).
After pulling this branch down, run the following commands in the faustjs monorepo:
1. run `npm install` 
2. run `npm run build` 
3. run `npm run build -w packages/block-editor-utils`
4. run `cd packages/block-editor-utils`
Switch to your testing site's repo.
npx @wordpress/create-block hello-world-block
7. cd to your new block plugin's folder 
8. Inside the …
> Merl 1153 faustwp block editor block controls implement checkbox control

- .changeset/slimy-plants-enjoy.md
- examples/next/app-router/next.config.js
- package-lock.json
- packages/faustwp-core/src/config/withFaust.ts
- packages/faustwp-core/tests/config/withFaust.test.ts
Currently the `x-using` Faust header will not render when i18n is set in `next.config.js` since we are using the `/(.*)` source regex. Next.js suggests we use the `/:path*` regex if you want to capture i18n routes as well:
```
// this gets converted to /(en|fr|de)/(.*) so will not match the top-level
// `/` or `/fr` routes like /:path* would
source: '/(.*)',
```
See: https://nextjs.org/docs/pages/api-reference/next-config-js/headers#headers-with-i18n-support
This is likely why we thought SSG could not render this header in the og PR:
https://github.com/wpengine/faustjs/pull/1215
However, after testing with this new regex, both SSG and SSR pages show the proper header.
1. From the canary branch, run the example project `npm run dev -w @faustwp/getting-started-example`
2. Go to …
> Fix `x-using` header

- .changeset/config.json
This PR fixes deep deps causing major bumps by using the `onlyUpdatePeerDependentsWhenOutOfRange` changesets flag. We had defined it before, but it looks like it had to be wrapped in a `___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH` object.
Reference:
Changesets decisions on versioning packages with peer deps:
https://github.com/changesets/changesets/blob/main/docs/decisions.md#the-versioning-of-peer-dependencies
Reference package that is using `onlyUpdatePeerDependentsWhenOutOfRange`:
https://github.com/statelyai/xstate/blob/c967791c82756b8c743c70a4a0b66b2e9e1d7d41/.changeset/config.json#L10
Some related issues:
https://github.com/changesets/changesets/issues/822
> Only update peer deps when out of range (Fixes peer deps causing major bump)

- .github/workflows/release-packages.yml
This PR fixes the `if` statement when versioning packages/deploying the WordPress plugin to wordpress.org. 
These changes were confirmed in a test repo available here:
https://github.com/blakewilson/deploy-wp-changesets-test
You can see the test version packages action results in the repo here that confirm that the variables are set properly, and that the if statement functions as expected:
https://github.com/blakewilson/deploy-wp-changesets-test/actions/runs/6634836225/job/18024831461
Additionally, here is the test/example workflow file:
https://github.com/blakewilson/deploy-wp-changesets-test/blob/main/.github/workflows/release.yml
> Fix deploy to wordpress.org workflow

- .github/workflows/e2e-next-example.yml
- .github/workflows/e2e-next-faustwp-example.yml
- .github/workflows/e2e-nightly-build.yml
Updates GitHub Actions workflows to specify v13 of `create-next-app`, to fix test failures [like these](https://github.com/wpengine/faustjs/actions/runs/6709125031) happening on all PRs right now.
Automated tests pass again
> ci: use `create-next-app@13` in e2e test workflows

- plugins/faustwp/readme.txt
Updated readme.txt test to version.
Ran the plugin against 6.4 RCx.
> MERL-1287: Update readme.txt for tested to version

- examples/next/app-router/package.json
- examples/next/block-support/package.json
- examples/next/faustwp-getting-started/package.json
Adds the caret to allow updates that are compatible, instead of pinning to a single version that requires we update this all the time.
> chore: Update @faustwp/cli and @faustwp/core packages in examples.

- .changeset/breezy-dragons-appear.md
- package.json
Since we removed the experimental app router package from the "build" step to not conflict with our workflows re:node/next required versions, the build was excluded from the release packages action, and thus published a broken build. This fixes the workflow and adds a changeset to make a corrective follow up release.
> Fix app router build publish

- .changeset/shy-pumas-grab.md
- packages/faustwp-cli/src/blockset.ts
Fixes a bug when blockset cli command fails to complete when a path to the output-folder contains spaces:
The following error happens when you use `faust blockset` command when running the project root that contains a space in the path:
```
❯ npm run blockset
> @faustwp/block-support-example@0.1.0 blockset
> faust blockset
warn - Could not find FAUST_SECRET_KEY environment variable.
warn - Some functionality may be limited.
info - Faust: Compiling Blocks into /Users/theo.despoudis/Local Sites/my-app/.faust/build
...
ERROR in build
Module not found: Error: Can't resolve './Sites/my-app/.faust/build' in '/Users/theo.despoudis/Local Sites/my-app'
resolve './Sites/my-app/.faust/build' in '/Users/theo.despoudis/Local Sites/my-app'
using description file: /Users/theo.despoudis/Local …
```
> Bug: Fix blockset cli failing when path contains spaces

- plugins/faustwp/includes/rest/callbacks.php
- plugins/faustwp/includes/telemetry/functions.php
- plugins/faustwp/tests/integration/ProcessTelemetryRouteTests.php
This PR creates a REST endpoint that accepts a body from the CLI, merges that data with data from WordPress, and then sends it off to GA if the user has Faust telemetry activated on WordPress.
The body looks like:
```
{
"node_faustwp_core_version": "xxxx",
"node_faustwp_cli_version": "xxxx",
"node_faustwp_blocks_version": "xxxx",
"node_apollo_client_version": "xxxx",
"node_version": "xxxx",
"node_next_version": "xxxx",
"node_is_development": "xxxx",
"command": "xxxx"
}
```
1. Checkout this branch
2. Make a request to `/wp-json/faustwp/v1/process_telemetry` and see the `401` response since you didn't pass a secret key
3. Add the secret key as the header `x-faustwp-secret` and verify you got a `204` response (no content).
4. Modify the `get_telemetry_client_id` function to return a string …
> Create process telemetry rest route

- plugins/faustwp/includes/rest/callbacks.php
- plugins/faustwp/includes/settings/callbacks.php
- plugins/faustwp/includes/settings/functions.php
- plugins/faustwp/includes/telemetry/functions.php
- plugins/faustwp/tests/integration/ProcessTelemetryRouteTests.php
- plugins/faustwp/tests/integration/TelemetryCallbacksTests.php
- plugins/faustwp/tests/integration/TelemetryFunctionsTests.php
Generates and saves a uuid for use with anonymous opt-in telemetry requests.
Check out this branch and do one or both of these:
- run `get_telemetry_client_id()` and notice it returns a uuid.
- make a mock telemetry call to the REST route
Note there is a uuid stored in `wp_options.faustwp_settings`.
> Generate UUID v4 for telemetry ID

- .changeset/brave-horses-laugh.md
- plugins/faustwp/includes/deny-public-access/callbacks.php
- plugins/faustwp/tests/acceptance/DenyPublicAccessCest.php
Fixes: https://github.com/wpengine/faustjs/issues/1699
1. Ensure Public Route Redirects is checked
2. Visit the robots.txt file from the WP instance. It should be accessible
> [FaustWP] Ignore robots in plugin redirects

- plugins/faustwp/includes/replacement/callbacks.php
This fixes the term_link filter callback to not modify the term link urls for GraphQL requests. 
fixes: #1613
replaces: https://github.com/wpengine/faustjs/pull/1616
Term uri is absolute in the GraphQL Response
The term uri is relative in the GraphQL response
But in the admin UIs the term links are absolute with the alternate Faust front-end domain.
> fix: term_link filter

- packages/faustwp-cli/src/index.ts
- plugins/faustwp/includes/rest/callbacks.php
Unblocks the `wp_remote_post()` call for anonymous opt-in telemetry.
Fixes a couple other small issues.
If you are opted in under Faust > Settings, any of the npm scripts (`dev`, `build`, `generate`, etc.) should result in an event showing up in GA, with associated telemetry data.
> Fix anonymous opt-in 

- .changeset/shaggy-cooks-dream.md
- .changeset/tame-ears-flash.md
- package-lock.json
- packages/faustwp-core/src/auth/authorize.ts
- packages/faustwp-core/src/components/WordPressTemplate.tsx
- packages/faustwp-core/src/hooks/useAuth.tsx
- packages/faustwp-core/tests/hooks/useAuth.test.ts
This PR skips the `useAuth` call unless the route is a preview route. Currently, `useAuth` is running on every page, which in turn makes a request to the token endpoint to see if a user is authenticated.
1. Checkout this branch
2. `npm install` from the root
3. `npm run build` from the root
4. Run the example project `npm run dev -w @faustwp/getting-started-example` from the root
5. Ensure all pages/posts/previews/etc operate as normal while checking to ensure there is not an additional token request made (there will still be a request for the token if `experimentalToolbar` is enabled)
6. Ensure `useAuth` hook operates as normal/expected with and without the new `skip` option.
Closes #1722
> Fix 401 token request in WordPressTemplate

- .changeset/mighty-chefs-peel.md
- internal/legacy.faustjs.org/docusaurus.config.js
- packages/core/README.md
- packages/next/README.md
- packages/react/README.md
Adds deprecation notices to `@faustjs/core`, `@faustjs/react`, and `@faustjs/next` legacy packages. These can be observed here:
- https://github.com/wpengine/faustjs/tree/faust-deprecation-notices/packages/core
- https://github.com/wpengine/faustjs/tree/faust-deprecation-notices/packages/react
- https://github.com/wpengine/faustjs/tree/faust-deprecation-notices/packages/next
This PR also makes the legacy.faustjs.org banner more clean that Faust.js (GQty) has been deprecated and when support will end. This can be tested and observed by checking out this branch, `cd internal/legacy.faustjs.org`, `npm install`, then `npm run dev`
Once these changes have been merged and a new release is cut, we'll finally want to `deprecate` these three packages within NPM: …
> Faust deprecation notices

- .changeset/mighty-chefs-peel.md
- examples/next/getting-started/package.json
- internal/legacy.faustjs.org/docusaurus.config.js
- packages/core/CHANGELOG.md
- packages/core/README.md
- packages/core/package.json
- packages/next/CHANGELOG.md
- packages/next/README.md
- packages/next/package.json
- packages/react/CHANGELOG.md
- packages/react/README.md
- packages/react/package.json
> Sync `canary` -> `main`

- .changeset/modern-walls-destroy.md
- package-lock.json
- packages/faustwp-core/src/components/FaustProvider.tsx
Fixes #1731 
Reproduce steps in #1731 but noticed the correct expected behavior.
> Fix error on page transition with multiple queries

- .github/workflows/nextjs-bundle-analysis.yml
This PR adds a `continue-on-error` for the Next.js bundle workflow during the "comment" steps. The action we use can not write comments when the PR is from an outside contributor:
> Note: In public repositories this action does not work in pull_request workflows when triggered by forks. Any attempt will be met with the error, Resource not accessible by integration.
> https://github.com/peter-evans/create-or-update-comment
So this PR will allow us to continue to use the Next.js bundle workflow, but also will not fail for outside contributors.
> Add `continue-on-error` for next bundle workflow for outside contributors

- .changeset/neat-foxes-develop.md
- package-lock.json
- packages/faustwp-cli/src/healthCheck/validateFaustEnvVars.ts
- packages/faustwp-cli/tests/healthCheck/validateFaustEnvVars.test.ts
This PR recommends the user update their NEXT_PUBLIC_WORDPRESS_URL to use the `wpenginepowered.com` TLD if they are using the `wpengine.com` TLD.
Unit tests have been provided. However, you can manually test this PR by:
1. Checking out this branch
2. `npm install`
3. `npm run build`
4. Set the `NEXT_PUBLIC_WORDPRESS_URL` in `examples/next/faustwp-getting-started/.env.local` to a `https://xxxxx.wpengine.com` URL.
5. Run the example project `npm run dev -w @faustwp/getting-started-example`
6. Notice the info text in the terminal
> Detect NEXT_PUBLIC_WORDPRESS_URL using wpengine.com TLD and recommend using wpenginepowered.com TLD

- examples/next/app-router/next.config.js
- examples/next/app-router/package.json
- examples/next/block-support/next.config.js
- examples/next/block-support/package.json
- examples/next/faustwp-getting-started/next.config.js
- examples/next/faustwp-getting-started/package.json
- package-lock.json
Adds `next-secure-headers` in all example projects, providing secure default header configuration across the site.
-Build and run one of the example projects
-Inspect the response headers of each page. It should have the following headers as defined in the [package doc](https://github.com/jagaapple/next-secure-headers?tab=readme-ov-file#next-secure-headers-vs-helmet)
|                                   | next-secure-headers     | Helmet                  | Comment                                                                                           |
|-----------------------------------|-------------------------|-------------------------|---------------------------------------------------------------------------------------------------|
| Strict-Transport-Security         | …
> Add next-secure-headers in example projects

- .changeset/modern-tools-collect.md
- package-lock.json
- packages/faustwp-cli/package.json
- packages/faustwp-cli/src/healthCheck/validateFaustEnvVars.ts
- packages/faustwp-cli/src/healthCheck/validateNextWordPressUrl.ts
- packages/faustwp-cli/tests/healthCheck/validateFaustEnvVars.test.ts
- packages/faustwp-cli/tests/healthCheck/validateNextWordPressUrl.test.ts
- packages/faustwp-cli/tests/healthCheck/verifyGraphQLEndpoint.test.ts
- plugins/faustwp/includes/rest/callbacks.php
- plugins/faustwp/includes/utilities/functions.php
- plugins/faustwp/tests/unit/FunctionsTests.php
This pull request adds a check in order to alert Faust users if they accidentally set the NEXT_PUBLIC_WORDPRESS_URL to the URL of their headless site. The code now makes a request to the FaustWP endpoint and checks if the response indicates that the URL is pointing to a headless site.
Closes #1750 
To test these changes, follow these steps:
1. In the Faust Plugin Settings, set the Headless URL to match the NEXT_PUBLIC_WORDPRESS_URL.
2. Try to run the dev or build commands in your headless site.
Observe that it should error with the following message:
```
Validation Failed: Ensure your NEXT_PUBLIC_WORDPRESS_URL does not match with Headless URL in the Faust WordPress plugin settings
```
To test these changes on older versions of the Faust Plugin, follow these steps:
1) In the Faust Plugin …
> Feature: Error when NEXT_PUBLIC_WORDPRESS_URL same as headless site URL

- .changeset/soft-swans-chew.md
- package-lock.json
- packages/faustwp-core/package.json
- packages/faustwp-core/src/apollo/errorLoggingLink.ts
- packages/faustwp-core/src/apollo/index.ts
- packages/faustwp-core/src/client.ts
- packages/faustwp-core/tests/apollo/errorLoggingLink.test.ts
Implemented `ErrorLoggingLink` class to capture GraphQL errors and server errors, providing enhanced error handling and logging capabilities. 
This class intercepts GraphQL operation requests and logs any encountered errors, including GraphQL errors and server errors, to the console.
#1732 
1. In the example project, try to add a graphQL field that does not exist. For example, in front-page template;
```
Component.query = gql`
${BlogInfoFragment}
${NavigationMenu.fragments.entry}
query GetPageData(
$headerLocation: MenuLocationEnum
$footerLocation: MenuLocationEnum
) {
generalSettings {
...BlogInfoFragment
}
nonExistingField
...
```
Now try to build the example project. It should fail while printing the graphQL error message into the console:
```
error - GraphQL errors: [
{
message: …
```
> Feat: Added Error Logging Apollo Link

- .changeset/cool-stingrays-hammer.md
- packages/experimental-app-router/src/server/routeHandler/index.ts
When `trailingSlash` is set to `true` in `next.config.js` ([Reference](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash)), the route handler doesn't handle the `pathname` with a trailing slash and returns a 404 ([Reference](https://github.com/wpengine/faustjs/blob/4724719eaa36295733955d47ad98c43e06ebc1f7/packages/experimental-app-router/src/server/routeHandler/index.ts#L8)). In the console you'll see `There was an error fetching the access token Error: Invalid response from token endpoint`.
> update @experimental-app-router for handle trailing slash config

- .changeset/smooth-dogs-cough.md
- packages/faustwp-core/src/components/Toolbar/nodes/MyAccount.tsx
- packages/faustwp-core/src/hooks/useAuth.tsx
- packages/faustwp-core/tests/hooks/useAuth.test.ts
Currently when avatars are disabled in WP, the Faust Toolbar loads them anyway. It should respect the Avatar Display option in WP. This PR works with the most recent change to avatar settings in WPGraphQL to ensure the avatar renders conditionally in the Faust Toolbar.
#1817 
**Note:** if WPGraphQL has not had a release containing [changes to the avatar setting](https://github.com/wp-graphql/wp-graphql/pull/3067) by the time you review this PR, then you will need to ensure your test site is using a symlinked WPGraphQL plugin that is set to the `develop` branch. If there has been a recent release containing this change, you can skip to the next set of testing instructions below.
1. Clone down the [WPGraphQL plugin](https://github.com/wp-graphql/wp-graphql).
2. In its repo, run `composer i` …
> Toolbar should respect show avatars setting in wp

- .changeset/quiet-avocados-turn.md
- packages/faustwp-core/src/getWordPressProps.tsx
Faust Templates do not recognize the 'Component.queries` portion when in TypeScript. This change will add multiple queries to the interface for FaustTemplate, which will resolve this issue.
#1825 
If you already have a TypeScript Faust app, you can run test the package changes there (note: do not use the `faust-scaffold-ts`, as the React version discrepancy will throw an error). If you do not have a TypeScript Faust app, skip this section and head down to the next section to set up testing from within an example project in the Faust monorepo.
If you already have a TypeScript Faust app, you can run test the package changes there by doing the following:
1.  In this branch,`cd` into the `packages/faustwp-core`.
2.  Run `npm link`
3.  Head over to your test site's repo. from within this repo, …
> Added multiple queries to interface for FaustTemplate

- plugins/faustwp/readme.txt
[Internal logistics tracking](https://github.com/orgs/wpengine/projects/13/views/1?pane=issue&itemId=56809132) 
I tested our wp-graphql-content-blocks plugin with the [WordPress Beta Tester](https://wordpress.org/extend/plugins/wordpress-beta-tester/) plugin. After uploading this testing plugin, I changed the settings of the plugin to the following to enable v6.5 testing: 
I then updated WordPress to version 6.5-RC3:
I then made a post with various media types, including gallery blocks, and ensured they are still appearing as expected (see screenshots section for a quick video). Note: during testing, be sure to set the media urls to the below in Faust: 
There does not appear to be any breaking changes upon the update.
https://github.com/wpengine/faustjs/assets/50935135/c92068ec-b5e2-4673-8 …
> Changed 'tested up to' in readme.txt to 6.5

- package-lock.json
- packages/faustwp-core/package.json
- packages/faustwp-core/src/apollo/errorLoggingLink.ts
- packages/faustwp-core/src/client.ts
Fixes an issue that happens when you run the example project with the latest canary changes.
1. Run the example project: `npm run dev -w examples/next/faustwp-getting-started` 
2. It  should work as expected, and no errors will be shown in the front-page.
This was the error message shown before this fix using latest canary:
> Fix: Fix issue with errorLoggingLink

- .changeset/red-dots-juggle.md
- plugins/faustwp/includes/settings/functions.php
- plugins/faustwp/tests/acceptance/SettingsCest.php
Sets the default for `enable_image_source` to true without affecting existing settings.
#1849 
As this is a toggle of a default, no further testing has been added
N/A
N/A
N/A
> feat: Set `enable_image_source` to on by default

- .github/workflows/e2e-next-example.yml
- .github/workflows/e2e-next-faustwp-example.yml
- .github/workflows/e2e-nightly-build.yml
- .github/workflows/e2e-test-plugin.yml
- .github/workflows/test-plugin-nightly.yml
- .github/workflows/test-plugin.yml
- .github/workflows/unit-test-packages.yml
- .github/workflows/unit-test-plugin-nightly.yml
- .github/workflows/unit-test-plugin.yml
- plugins/faustwp/.docker/Dockerfile
- plugins/faustwp/docker-compose.yml
1. Updates the plugin unit tests to include WordPress 6.1, 6.2, 6.5 and WordPress Nightly. This better matches our testing strategy with the content blocks plugin.
2. Ceans up some of it's testing steps
3. Ensures the PHP version in Dockerfile can be set by specifying it in the parent image
4. Updates existing E2E tests for the plugin to work with the updated Dockerfile
5. Ensures plugin E2E tests no longer overwrite the PHP version provided by the image
6. Normalizes workflow naming for better identification of workflows and their results
> Update plugin unit testing with more WordPress versions and Nightly WordPress builds

- .changeset/fair-rocks-promise.md
- plugins/faustwp/includes/rest/callbacks.php
- plugins/faustwp/includes/utilities/functions.php
- plugins/faustwp/tests/unit/FunctionsTests.php
This PR enhances the domain_match function to handle a wider range of scenarios, including different ports, schemes, and subdomains. It also adds a comprehensive set of test cases to ensure the function behaves correctly in various situations.
(https://github.com/wpengine/faustjs/issues/1884)
1. Create a front end Node environment runs on localhost:3000, and LocalWP environment runs on localhost with a different port.
2. Run the development server using `npm run dev -w examples/next/faustwp-getting-started`
3. The CLI tool should not fail the health check for WordPress URL validation.
Alternatively if you can also try create a new front end Node environment with the same host as the LocalWP environment but in a different port.
>  Improve domain_match Function and add test cases

- plugins/faustwp/.phpcs.xml.dist
- plugins/faustwp/composer.json
- plugins/faustwp/composer.lock
- plugins/faustwp/faustwp.php
- plugins/faustwp/includes/replacement/functions.php
- plugins/faustwp/includes/settings/functions.php
Per https://github.com/squizlabs/PHP_CodeSniffer/issues/3932, we don't actually need to update the package name as they were able to maintain the name on package. That said, our implementation is still out of date.
- #1827 
As code is to existing tests, no additional testing has been implemented.
> Update PHPCS and coding standards to the current version.

- package-lock.json
- package.json
Adds the `react-refresh` package, which is required during many builds, to avoid having to remember to manually install it when working with Faust. This should make it easier for new devs.
> Adds the `react-refresh` package to avoid having to manually do so.

- .changeset/orange-birds-invent.md
- packages/block-editor-utils/src/controls/TextArea.tsx
- packages/block-editor-utils/src/controls/index.ts
This PR adds a missing TextAreaControl within the custom block editorFields configuration.
https://github.com/wpengine/faustjs/issues/1895
1. Inside the `/example/next/block-support` package add the following fields in the block-b Component.config that includes a `control: 'textarea'`
```js
Component.config = {
name: 'CreateBlockBlockB',
editorFields: {
message: {
type: 'string',
label: 'My Message',
location: 'editor',
},
textArea: {
type: 'string',
label: 'My Message',
location: 'editor',
control: 'textarea'
},
},
};
```
Also update the block.json to recognize the new attribute
```js
"attributes": {
"message": {
"type": "string",
"default": "Hello World"
},
"textArea": {
"type": "string",
"default": "Hello World"
},
```
2. Build and push the blocks to WordPress:
```
$ npm run blockset …
```
> [Bug] Add missing textarea control handler.

- .changeset/wet-ladybugs-rush.md
- plugins/faustwp/includes/blocks/functions.php
Fixes issue when blocks not showing in the block editor when running the `blockset` command on WP >=v6.5 
https://github.com/wpengine/faustjs/issues/1880
1. Run `faust blockset` to publish blocks from the `examples/next/block-support` package on a Wordpress Version 6.5 or higher
2. Blocks should show in the editor list. Previously the blocks would not appear in this list.
> Bug: Fixes issue with blocks not showing in the block editor when running blockset command on WP >=v6.5

- .changeset/heavy-rats-enjoy.md
- packages/faustwp-core/src/components/WordPressTemplate.tsx
- packages/faustwp-core/src/utils/isWordPressPreview.ts
- packages/faustwp-core/tests/components/WordPressTemplate.test.tsx
- packages/faustwp-core/tests/utils/isWordPressPreview.test.ts
This PR addresses a bug in the WordPressTemplate component where the detection of WordPress preview URLs was overly broad, potentially catching non-WordPress preview URLs. The fix introduces a more precise method for determining if the URL is a WordPress preview.
https://github.com/wpengine/faustjs/issues/1903
The previous implementation checked if the URL query string contained preview=true using a simple string includes method. This approach could incorrectly identify non-WordPress previews as WordPress previews if they happened to have a similar query parameter structure.
* Introduced a utility function isWordPressPreview to accurately check for the presence of preview=true in the URL query parameters.
* Updated the WordPressTemplate component to use this utility function for …
> Fix: Ensure Accurate Detection of WordPress Previews via URL Query Parameters

- .changeset/fast-queens-dress.md
- .github/workflows/e2e-test-plugin.yml
- .github/workflows/unit-test-plugin-nightly.yml
- .github/workflows/unit-test-plugin.yml
- plugins/faustwp/includes/menus/callbacks.php
- plugins/faustwp/includes/settings/callbacks.php
- plugins/faustwp/tests/acceptance/SettingsCest.php
Currently when the FaustWP plugin is active, all registered Nav Menu locations are removed. 
While some users want to use Faust to manage their menu locations, some users manage menu locations in code or using other plugins and do not want Faust to remove all other menu locations. 
This PR adds a new setting that allows user to opt-in or out of the removal of non-Faust Nav Menu locations.
closes #1925 
With the following code in place: 
```php
function register_my_menus() {
register_nav_menu( 'test-primary', __( 'Test Primary Menu' ) );
}
add_action( 'after_setup_theme', 'register_my_menus' );
```
If the setting is checked:
Then I have only the 2 Faust registered menus in the WP Nav Menu Manager:
And if the setting is NOT checked:
Then I have the 2 Faust Menus as well as the menu …
> fix: only remove non-faust Nav Menu locations if the user opts-in to it

- .changeset/long-humans-type.md
- examples/next/block-support/.env.local.sample
- examples/next/block-support/pages/sitemap.xml.js
- packages/faustwp-core/src/server/sitemaps/createSitemaps.ts
- packages/faustwp-core/src/server/sitemaps/getSitemapProps.tsx
This PR introduces a new feature allowing the configuration of a custom sitemap index path via the `sitemapIndexPath` option in the getSitemapProps function. This is particularly useful for ensuring compatibility with WordPress plugins like RankMath that modify the default sitemap path.
To configure a custom sitemap index path, update your getServerSideProps function in your Next.js page as follows:
```js
import { getSitemapProps } from '@faustwp/core';
export default function Sitemap() {}
export function getServerSideProps(ctx) {
return getSitemapProps(ctx, {
sitemapIndexPath: '/sitemap_index.xml', // Specify the custom sitemap index path
frontendUrl: process.env.NEXT_PUBLIC_SITE_URL,
});
}
```
This is particularly useful when using WordPress plugins like RankMath that change the default …
> Introduce configurable "sitemap index path" for enhanced plugin compatibility

- .changeset/tiny-years-grin.md
- .changeset/wet-camels-lick.md
- package-lock.json
- packages/faustwp-cli/package.json
- packages/faustwp-core/src/components/WordPressTemplate.tsx
This fixes a bug where the `WordPressTemplate` component would return `null` on the server when `isPreview` was null.
fixes #1813 
I tested following the steps outlined in #1813 on the reproduction mentioned in the issue. 
I also was able to reproduce the issue on acf.wpgraphql.com (codebase here: https://github.com/wp-graphql/acf.wpgraphql.com) and was able to confirm that the issue is resolved for acf.wpgraphql.com with this fix in place. 
With JavaScript disabled, the page is blank
Content is rendered even with JavaScript disabled
With JavaScript disabled, the page is blank
Content is rendered even with JavaScript disabled
> fix: ssr not always working

- .changeset/poor-cats-arrive.md
- plugins/faustwp/readme.txt
This PR is a follow up to https://github.com/wpengine/faustjs/pull/1928, aiming to kick off a new deploy of the plugin to WordPress.org that was previously failing.
> Update "tested up to" version for faustwp WordPress plugin.

- .changeset/eleven-oranges-hope.md
- plugins/faustwp/faustwp.php
- plugins/faustwp/includes/updates/check-for-updates.php
- plugins/faustwp/includes/updates/class-plugin-updater.php
- plugins/faustwp/includes/updates/plugin-updater.php
Introduced a PluginUpdater class for FaustWP that allows plugins to receive updates from a custom API endpoint (https://wpe-plugin-updates.wpengine.com/). This class registers hooks to override update notifications and fetch information from the custom API. Key changes include:
- Added a mechanism to define plugin properties and cache update checks.
- Implemented transient caching to reduce API requests.
- Hooked into WordPress’s update system (`plugins_api`, `pre_set_site_transient_update_plugins`) for fetching and displaying plugin update details.
> feat: Add PluginUpdater to Support Plugin Updates from Custom API

- .changeset/smart-pumas-act.md
- packages/blocks/src/blocks/CoreButton.tsx
- packages/blocks/src/blocks/CoreQuote.tsx
- update query fragment on CoreQuote to be compatible with WordPress 6.6
closes #1932
> fix: cannot query field "align" on type "CoreQuoteAttributes"'

- examples/next/custom-toolbar/package-lock.json
- examples/next/custom-toolbar/package.json
* Updates dependencies on the custom toolbar example project including next.js to 14.2.7
> Update deps in custom-toolbar example
